### ISSUE TITLE
Add support for grpc-dagger

### ISSUE THREAD

**Issue by KristiyanGergov** [grpc/grpc-kotlin#100]
If I try to use [grpc-dagger](https://dagger.dev/dev-guide/grpc.html) with a service generated by [protoc-gen-grpc-kotlin](https://github.com/grpc/grpc-kotlin/tree/master/compiler), I am getting the following error: 

```
e: /Users/..../FooService.java:6: error: FooServiceGrpcKt is not a gRPC service class
@dagger.grpc.server.GrpcService(grpcClass = FooServiceGrpcKt.class)
```

```
@GrpcService(grpcClass = FooServiceGrpcKt::class)
class Foo @Inject constructor() : FooServiceGrpcKt.FooServiceCoroutineImplBase()
```

Are you thinking of adding support for it, or am I just doing something the wrong way?

**Comment by lowasser** [comment]
I think this is a feature request for grpc-dagger, rather than for grpc-kotlin?

**Comment by bubenheimer** [comment]
@lowasser could it make sense to bring up dagger-grpc support for grpc-kotlin directly from your end? This issue, https://github.com/google/dagger/issues/1978, seems to suggest that it's not on the dagger-grpc project's radar. That's somewhat of a blocker for grpc-kotlin server usage.
