### ISSUE TITLE
Android sample

### ISSUE THREAD

**Issue by Xtizainy** [grpc/grpc-kotlin#103]
Could you please provide example project for android?

**Comment by donpaul120** [comment]
I support this...
The current example using protobuf-lite leads to errors e.g

`Duplicate class com.google.protobuf.WireFormat$Utf8Validation$2 found in modules jetified-protobuf-java-3.11.0.jar (com.google.protobuf:protobuf-java:3.11.0) and jetified-protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0)`

**Comment by Xtizainy** [comment]
@jamesward any updates on this?

**Comment by bshaffer** [comment]
This may be related to #118

**Comment by jamesward** [comment]
Here is an android sample (awaiting merge): https://github.com/jamesward/kotlin-samples/tree/sample-android/run/grpc-sample-android

Let me know if you have any questions about it!

**Comment by chalin** [comment]
@jamesward - thanks for the sample! (Btw, I tried the cloud run, but it seems stuck "Waiting for your approval to 'Authorize' Cloud Shell ...". I'm not seeing a prompt that would allow me to authorize it.

@davidjwiner, @jamesward, et all: would it make sense to migrate the example code to this repo? (I'm not saying it should, I'm just asking what the team feels is best) Regardless, I think that we should add at least a reference to the example on grpc.io, e.g., in the [grpc.io Kotlin page](https://grpc.io/docs/languages/kotlin). Would you agree?

**Comment by jamesward** [comment]
I've occasionally seen Cloud Run Button getting stuck on the `Authorize` step.  But usually works if I try again.  Can you try that one more time?

Yeah, I'm not sure where is the best place for this or other samples.  Happy to move them wherever.
