### ISSUE TITLE
Rich grpc Error model management

### ISSUE THREAD

**Issue by protheusfr** [grpc/grpc-kotlin#104]
Hello,

I can't find in examples or (light) documentation how to use hRPC rich error model.
For exemple how to reply with a `GRPC_STATUS_INTERNAL` or `GRPC_STATUS_UNAUTHENTICATED` from server side ?

**Comment by lowasser** [comment]
The solution is to throw a `StatusException` with `Status.INTERNAL` or any other custom Status.  We could definitely document this better, I'll see what we can do.

**Comment by lowasser** [comment]
Notably, the documentation in the *generated code* does explain this.  See the doc generation code here, for example: https://github.com/grpc/grpc-kotlin/blob/master/compiler/src/main/java/io/grpc/kotlin/generator/GrpcCoroutineServerGenerator.kt#L217

**Comment by protheusfr** [comment]
Thank you @lowasser , I confirm, the documentation could be improved on this point ;-)

**Comment by protheusfr** [comment]
Any way to provide additional error message with exception ?

**Comment by lowasser** [comment]
Sure: use `Status.withDescription` before passing it to the `StatusException` constructor.

**Comment by protheusfr** [comment]
Many thanks !
