### ISSUE TITLE
grpc-kotlin-compiler should be able to build on windows

### ISSUE THREAD

**Issue by bshaffer** [grpc/grpc-kotlin#116]
In order for us to truly run tests on Windows, we need to be able to build the protoc plugin on Windows. Right now we receive the following error:

```
Execution failed for task ':grpc-kotlin-compiler:generateTestProto'.
> protoc: stdout: . stderr: --grpckt_out: protoc-gen-grpckt: %1 is not a valid Win32 application.
```

Once we can build the plugin on Windows as expected, we can add `windows-latest` to the operating system matrix in our github actions config. This may be fixed once we resolve #82 .

**Comment by cbeaujoin** [comment]
I have the same problem with windows.
Any update ?

**Comment by jamesward** [comment]
This should work now with the jar-based protoc plugin.  Please re-open if not.
