### ISSUE TITLE
stub-lite Doesn't Seem to Work

### ISSUE THREAD

**Issue by jamesward** [grpc/grpc-kotlin#118]
I tried using stub-lite on a project that only compiled protos but the compile failed on some imports, like:
`import io.grpc.kotlin.AbstractCoroutineServerImpl`

Maybe I'm using it wrong.

**Comment by jamesward** [comment]
I think I have this working now.  Here is the `build.gradle.kts`:
```
import com.google.protobuf.gradle.*

plugins {
    kotlin("jvm")
    id("com.google.protobuf") version "0.8.12"
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("javax.annotation:javax.annotation-api:1.2")
    api("io.grpc:grpc-protobuf-lite:${rootProject.ext["grpcVersion"]}")
    api("io.grpc:grpc-stub:${rootProject.ext["grpcVersion"]}")
    api("io.grpc:grpc-kotlin-stub:${rootProject.ext["grpcKotlinVersion"]}") {
        exclude("io.grpc", "grpc-protobuf")
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${rootProject.ext["protobufVersion"]}"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:${rootProject.ext["grpcVersion"]}"
        }
        id("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:${rootProject.ext["grpcKotlinVersion"]}"
        }
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.builtins {
                named("java") {
                    option("lite")
                }
            }
            it.plugins {
                id("grpc") {
                    option("lite")
                }
                id("grpckt") {
                    option("lite")
                }
            }
        }
    }
}
```

I think we'll need to document those `option("lite")` configs for `build.gradle` and `build.gradle.kts`.

Also note that I did my own `lite` `grpc-kotlin-stub` by excluding the transitive dep.

**Comment by Xtizainy** [comment]
Could you provide a link to sample app with the full code please?

**Comment by jamesward** [comment]
The project is a bit more than a simple lite sample, but here it is: https://github.com/jamesward/kotlin-samples/tree/master/run/grpc-sample-android
The build config: https://github.com/jamesward/kotlin-samples/blob/master/run/grpc-sample-android/common/build.gradle.kts

**Comment by bshaffer** [comment]
Adding "exclude" to `stub-lite/build.gradle` is not having any effect:

```
implentation("io.grpc:grpc-protobuf-lite:${rootProject.ext.grpcVersion}") {
        exclude group: "io.grpc", module: "grpc-protobuf")
    }
```

Running `../gradlew -q dependencies` still shows the `grpc.io:grpc-protobuf` dependency

**Comment by bshaffer** [comment]
Fixed it, I needed to have the exclude on `io.grpc:grpc-kotlin-stub`
