### ISSUE TITLE
A way to mark the end of the stream

### ISSUE THREAD

**Issue by KristiyanGergov** [grpc/grpc-kotlin#127]
With the java [StreamObserver](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html), you can call [onCompleted](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html#onCompleted--) to mark the end of the streaming. Is there a way we can do that with Flow? The thing I want to accomplish: 

With bidirectional streaming -> send data to the server, waits for its response and if successful send the next one. After all the data is send, notify the server that we finished.

**Comment by lowasser** [comment]
Completion is just indicated by ending the flow normally.  For example, `flow { emit(1); emit(2) }` emits `1` and `2` and then ends.

**Comment by lowasser** [comment]
It's worth mentioning that the "ping pong" model where requests depend on responses and vice versa is harder to do with flows, but can always be done with channels and the adapters between flows and channels (e.g. `Channel.consumeAsFlow`).  You can build channel-based helpers that let you do it in terms of flows, but these aren't always very intuitive.
