### ISSUE TITLE
Add Android client compatible with non-Android Greeter server

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#131]
@jamesward et all: would it be much effort to create a Kotlin version of the Android Java Hello World example, whose sources are here: https://github.com/grpc/grpc-java/tree/master/examples/android/helloworld? /cc @davidjwiner

**Comment by jamesward** [comment]
I have an Android sample in a PR now: https://github.com/GoogleCloudPlatform/kotlin-samples/pull/67

It wasn't based on the sample you reference but I think that's ok.

**Comment by chalin** [comment]
Could you migrate the Android client code to this repo's `examples` folder?

**Comment by chalin** [comment]
Oh, I'd forgotten that this task had been assigned to me. I'll check that out next week.

**Comment by chalin** [comment]
@jamesward - will you update your example to use the canonical `helloworld.proto` or do you want me to do that too?

**Comment by jamesward** [comment]
Yup! On it.

**Comment by jamesward** [comment]
That is done

**Comment by chalin** [comment]
PR#137 takes a step in the direction of addressing this issue. We could merge it and then take the next steps to fold `examples-android` into `examples` after restructuring it to (possibly) he these top-level folders:

- `android-client`
- `client`
- `common` - for the `hello_world.proto` file
- `server`

**Comment by chalin** [comment]
While testing the changes for https://github.com/grpc/grpc-kotlin/pull/176#issuecomment-693487359, I was able to confirm that this issue has been fixed. Closing. Follow-up changes (the example source reorg) are being tracked via #138.
