### ISSUE TITLE
Make it nicer to use with Bazel

### ISSUE THREAD

**Issue by Kernald** [grpc/grpc-kotlin#133]
Implementing a service requires a dependency on `@com_github_grpc_grpc_kotlin//stub/src/main/java/io/grpc/kotlin:stub` (defined [here](https://github.com/grpc/grpc-kotlin/blob/2573cd4cb64e91b09fb34327bf2038c8342700b8/stub/src/main/java/io/grpc/kotlin/BUILD.bazel#L9)), which is not super easy to 1) discover 2) read. I understand that this is really early days, I was wondering if there were plans to export those core targets from the top-level `BUILD` file, or at the top of the package (e.g. in this case, `//stub:stub`), as [grpc-java does](https://github.com/grpc/grpc-java/blob/master/stub/BUILD.bazel)?

**Comment by Kernald** [comment]
I just realised that the target generated by `kt_jvm_grpc_library` exports those dependencies already, so it shouldn't be needed - IntelliJ isn't finding the super-class, but that's probably due to something else. Sorry for the noise.

**Comment by PedroSena** [comment]
@Kernald I'm running into this issue, how did you handle it ? You mentioned `kt_jvm_grpc_library` exports it but I'm running into this issue exactly when trying to use `kt_jvm_grpc_library`

**Comment by Kernald** [comment]
@PedroSena If the issue you have is that it compiles fine, but IntelliJ is complaining about missing symbols, you're most likely hitting the issue fixed in bazelbuild/rules_kotlin#338 - which hasn't been released yet.
