### ISSUE TITLE
Integrate `examples-android` into `examples`

### ISSUE THREAD

**Issue by jamesward** [grpc/grpc-kotlin#138]
Followup to #131 and #137.

Suggested `examples` layout:

- `android-client`
- `cli-client`
- `common`
- `server`

**Comment by chalin** [comment]
(A) I'd vote for just `client` instead of `cli-client`, with the understanding that it is the default client corresponding to the given server.

(B) Another possibility might be to have the following structure:

- `client`
  - `android`
  - `cli`

---

Although my preference would be for (A). Thoughts?

**Comment by jamesward** [comment]
Starting giving this a try but one issue with combining everything is the `lite` stubs.  For Android I think it's best to use them, and for non-Android it seems like we shouldn't.  But I'm not certain on that.  This variability would mean we should have separate samples but I'm not totally sure yet what the purpose of the lite versions is.  I need to investigate further or have someone with more knowledge help me understand this. :)

**Comment by jamesward** [comment]
Sounds like we should recommend a setup where the android project uses stub-lite and the others use the regular stubs.  In this case we need to split out `common` to:
- `protos`
- `stub`
- `stub-lite`

Where `android` depends on `stub-lite` and `client` and `server` depend on `stub`.  Let me know if anyone disagrees with this approach.

**Comment by chalin** [comment]
What would go in the `stub*` folders?

**Comment by jamesward** [comment]
Really nothing but gradle config that creates the jars used for the `client`, `server`, and `android` projects.  I looked into producing the different artifacts in the `common` project but couldn't figure out how to do it.

**Comment by chalin** [comment]
If it's just config, could we use a folder name that reflects that? Maybe `android-config` and `config`?

Any comments from @bshaffer @lowasser?

**Comment by bshaffer** [comment]
This directory structure is confusing to me. Why is there a `common` directory? It would make more sense to me to open up `examples` and see only `client` and `server`, and then be able to drill into `android-client` and `cli-client` or something along those lines.

**Comment by jamesward** [comment]
The protos should be in a shared project.  I'd called that `common` but it could also be called `protos` or something.  We could nest the clients and servers.  I'm cool with that.

**Comment by bshaffer** [comment]
+1 for naming the directory `protos`!

**Comment by chalin** [comment]
Any progress on this?

**Comment by jamesward** [comment]
I have this all working, but I need to update the `README.md` instructions. Should have a PR ready in the next couple days.

**Comment by bshaffer** [comment]
This has been fixed by #183

**Comment by chalin** [comment]
Great job @jamesward! 🎉
