### ISSUE TITLE
IntelliJ Setup

### ISSUE THREAD

**Issue by metarag** [grpc/grpc-kotlin#142]
Potential noob question here. How do you set up `examples/` in IntelliJ. 

I'm on IntelliJ Ultimate Edition 2020.1.3 and I ran
```bash
./gradlew installDist
```

Still getting these red squiggles in my IDE

<img width="1792" alt="Screen Shot 2020-07-10 at 3 29 00 PM" src="https://user-images.githubusercontent.com/12293899/87208186-b25b6700-c2c2-11ea-953f-12b8d8c0c2d3.png">

I even tried marking the following dirs as "Generated Sources Root" but no luck
- `build/generated/source/proto/main/grpc`
- `build/generated/source/proto/main/grpckt`
- `build/generated/source/proto/main/java`

Is there extra configuration that needs to be done? If so, is there a way to do this in `build.gradle.kts` so the configuration can be shared with everyone on the team?

**Comment by jamesward** [comment]
Try to add this to your `build.gradle.kts`:
```
sourceSets {
    val main by getting
    main.java.srcDirs("build/generated/source/proto/main/java")
    main.java.srcDirs("build/generated/source/proto/main/grpc")
    main.java.srcDirs("build/generated/source/proto/main/grpckt")
}
```

**Comment by metarag** [comment]
Yep! That worked 🙂

Was still getting the following error on the line `val main by getting`
```
Type 'ExistingDomainObjectDelegate<out SourceSet!>' has no method 'getValue(Nothing?, KProperty<*>)' and thus it cannot serve as a delegate
```

Fixed by changing the line to
```kotlin
val main by getting {}
```

It would be nice to have this configuration checked into `examples/build.gradle.kts` if it doesn't cause any unintended effects.

**Comment by jamesward** [comment]
Thanks! I need to work on this more before integrating it because somehow the sources are getting compiled even though they aren't currently in a sourceset and adding the generated sources to a sourceset manually seems like it could cause issues. So more investigation is needed.
