### ISSUE TITLE
Bazel generator generates service bindings for only one file

### ISSUE THREAD

**Issue by pratik-brex** [grpc/grpc-kotlin#149]
To reproduce this is what, I had to do:

* A `proto_library` target with multiple files that define a grpc `service `. Lets say `a.proto`, `b.proto`, `c.proto` respectively defininely `service A`, `service B`, `service C`.
* Define a `kt_jvm_grpc` that depends on this `proto_library` and it's java bindings. The final JAR only has coroutine bindings for `service A` and while there are Java bindings for B and C, there are no kotlin bindings.

**Comment by bshaffer** [comment]
Summoning @fashing as he added the Bazel support in https://github.com/grpc/grpc-kotlin/pull/97
