### ISSUE TITLE
Can't publish to local maven repo

### ISSUE THREAD

**Issue by koyakei** [grpc/grpc-kotlin#150]
a5684bf18bfa903ce2498b67a6fcbff2d637ed0d
grpc-kotlin-stub -> Tasks -> build ->build
grpc-kotlin-stub -> Tasks -> distribution ->installDist
grpc-kotlin-stub -> Tasks -> publishing -> publishToMavenLocal

From GUI
![image](https://user-images.githubusercontent.com/4229382/89092486-20400d80-d3ed-11ea-86bf-b57574eb4574.png)

```
Execution failed for task ':grpc-kotlin-compiler:signMavenPublication'.
> Cannot perform signing task ':grpc-kotlin-compiler:signMavenPublication' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Then I add.
./gradle/gradle-wrapper.properties
```
signing.keyId=A1B2C3D4
signing.password=somePassword
signing.secretKeyRingFile=/Users/christiandrager/.gnupg/secring.gpg
```
But error was not changed 

From terminal
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

```

Should I sign it? even if I would push to local maven repo.

**Comment by jamesward** [comment]
Can you try to rename `~/.gradle/gradle-wrapper.properties` to `~/.gradle/gradle.properties` ?

**Comment by bshaffer** [comment]
This is fixed by https://github.com/grpc/grpc-kotlin/pull/203. The `publishToMavenLocal` task now skips over signing if a key is not defined.

try to now with v0.2.1!
