### ISSUE TITLE
Provide an example for compiling to native-image

### ISSUE THREAD

**Issue by eiswind** [grpc/grpc-kotlin#152]
I fail with and seemingly endless chain of problems when I try to build a native-image with graalvm.
Has anyone setup a working example?

**Comment by jamesward** [comment]
There is a lot of reflection happening under the covers so it probably is possible but not easy.  Are you looking to do this for server, client, or both?

**Comment by eiswind** [comment]
My primary target would be the client. I have seen that micronaut and quarkus are doing this for the java server side, but my target is a openjfx client.

**Comment by jamesward** [comment]
Cool.  One more question... Is it ok to use the `lite` client?

**Comment by eiswind** [comment]
Heya :) I do not have even a basic idea how this setup would look like :) Maybe you could point me to an example setup with the lite-client? ATM I have a shared module that contains the generated stubs and service skeletons, that I use on both sides.

**Comment by jamesward** [comment]
Cool.  I think `lite` should work.  I'll try to get a sample project going that creates a GraalVM native-image client.

**Comment by eiswind** [comment]
Ok I get it. Not using netty seems to be a good idea :)

**Comment by eiswind** [comment]
At least I could compile and connect it now with the lite-stubs. Now I see other troubles with openjfx :(
Thanks a lot for pointing me in the right direction.

**Comment by asarkar** [comment]
@eiswind Are you targeting JVM platform using lite? Would you be willing to share a sample project here since you say you got it working?

**Comment by eiswind** [comment]
@asarkar Unfortunately I cannot share this code. But it was a no brainer. As soon as I did remove netty and replaced it with the lite libs it did compile without any further effort.

**Comment by jamesward** [comment]
@asarkar You can find an example `lite` project build at: https://github.com/jamesward/kotlin-samples/blob/sample-android/run/grpc-sample-android/common/build.gradle.kts

**Comment by asarkar** [comment]
@jamesward I saw that one already, but I got the impression that @eiswind got lite working for JVM platform, not Android; I also asked specifically and wasn't refuted.
> Are you targeting JVM platform using lite?

**Comment by jamesward** [comment]
Cool.  My example does target the JVM.  But I'm working on another one that targets Android (AAR).  Is that what you are looking for?

**Comment by asarkar** [comment]
> My example does target the JVM

It does? The project name mislead me then.

<img width="500" alt="Screen Shot 2020-08-07 at 12 33 21 PM" src="https://user-images.githubusercontent.com/1302775/89681689-444a9580-d8aa-11ea-8124-880e4b535618.png">

i'll be happy with a JVM example.

**Comment by jamesward** [comment]
I used lite in the `common` subproject with the protos and grpc kotlin stuff.  It targets the JVM and is used in an android project and a JVM server project.
