### ISSUE TITLE
How to cancel the gRPC call?

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-kotlin#153]
Usually, the client can cancel the gRPC call with:
```
(requestObserver as ClientCallStreamObserver<Request>)
    .cancel("Cancelled", null)
```
How do I do this using this library where the `StreamObserver<Request>` is replaced by a `Flow<Request>`? There's no such thing as `Flow.cancel`.

**Comment by asarkar** [comment]
It seems `currentCoroutineContext()[Job]?.cancel()` will do the job. https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/ClientCalls.kt#L321

**Comment by lowasser** [comment]
Throwing an exception from the flow, cancelling the coroutine that is collecting the flow, or using a flow mechanism like `takeWhile` will all interrupt the flow and cancel the RPC.

**Comment by asarkar** [comment]
@lowasser 

> cancelling the coroutine that is collecting the flow

Isn't this the same as `currentCoroutineContext()[Job]?.cancel()`?  It'll throw a `CancellationException`.

`takeWhile` seems to throw `AbortFlowException`.

Throwing an exception for normal cancellation is undesirable, because it creates a stacktrace wasting time, and is also a poor substitute for control flow (no pun intended); however, it seems like the flow designers chose to make the flow not dissimilar to an infinite loop.

**Comment by bubenheimer** [comment]
@lowasser Could the generated stub API documentation be improved on this point? In particular it currently does not seem to specify whether, on the client, a bidi stub's response flow checks for cancellation on emit (may be the same for server-streaming stubs, I don't have any of those). I suppose this is common behavior for flows, and the current implementation does appear to behave this way, but I don't have the impression that it's guaranteed for flows in general. It's the question whether a flow collector needs to check for cancellation explicitly via `cancellable()` or similar.
