### ISSUE TITLE
Wrong Proto outer classname in generated code, does not compile 

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-kotlin#154]
Given a proto file `ServiceM`:
```
syntax = "proto3";
package com.mycompany;

service ServiceM {...}
message reqM {...}
```

Generated `object ServiceMGrpcKt` refers to `Servicem.reqM`, that doesn't exist. The correct outer classname is `ServiceMOuterClass`. This makes the plugin unusable unless the outer classname is explicitly specified in the proto file.

**Comment by asarkar** [comment]
Seems duplicate to https://github.com/grpc/grpc-kotlin/issues/92 that was closed in May but the "fix" is yet to be released.

**Comment by bshaffer** [comment]
This fix has been released for quite some time. Can you update your version to `0.1.4` and verify that it works for you now?

**Comment by asarkar** [comment]
@bshaffer I'm already on `0.1.4`, and confirm that this issue exists. I've updated my original post to include the proto file name, which seems to matter.

**Comment by bshaffer** [comment]
@asarkar Can you try updating to `0.1.5` and confirming the problem still exists?

**Comment by asarkar** [comment]
@bshaffer Tried `0.1.5`, and no good. I'm sorry, but it looks like you're throwing pasta at the wall hoping something would stick. Has there been a change in `0.1.5` that'd fix this issue?

**Comment by jamesward** [comment]
We have a bunch of examples that do not specify the class name, but work fine:
https://github.com/GoogleCloudPlatform/kotlin-samples/blob/master/run/grpc-hello-world-gradle/src/main/proto/hello_world.proto

Any ideas on what is different between these and yours?

**Comment by asarkar** [comment]
Here's a proto file that can be used to reproduce this issue. Rename to `.proto` since GH won't let me upload with the original extn.
[serviceT.txt](https://github.com/grpc/grpc-kotlin/files/5106289/serviceT.txt)

**Comment by asarkar** [comment]
@bshaffer I'm curious about the commit message, what is the style guide for proto files that wasn't followed in the example above?

**Comment by bshaffer** [comment]
@asarkar good question! We use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). TLDR it's a standardization to differ between BC breaking changes, features, fixes, and docs/chores.

**Comment by bshaffer** [comment]
Oh, I see you mean the contents of the commit message, not the format. The style guide recommends camel case, so it's in reference to that.

**Comment by asarkar** [comment]
> The style guide recommends camel case

https://developers.google.com/protocol-buffers/docs/style#message_and_field_names

I’m guessing you’re referring to the following:
> Use CamelCase (with an initial capital) for message names

and the name of the proto file is irrelevant. Correct?
