### ISSUE TITLE
Add a static factory method to create the stub

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-kotlin#163]
The usual way to create a client stub in Java is using one of the static factory methods named `new*Stub`. Consider adding such a method for consistency instead of invoking the constructor directly.

**Comment by lowasser** [comment]
What would this really buy us, though?  Using the constructor is more conventional for Kotlin, and we can't add the static method to the same place that Java's would be, so having a "static" (companion?) factory doesn't seem to actually provide much benefit.

**Comment by asarkar** [comment]
@lowasser It just makes it easier for people already familiar with grpc-java by following the same convention. The Java constructors are, in fact, `private`, and hence, can’t be invoked directly. Does it make sense to introduce a new paradigm in the Kotlin counterpart? Also, the choice of constructor vs static method isn’t a language choice, it’s a design choice; Java could’ve simply exposed the constructors but didn’t.

**Comment by lowasser** [comment]
There is a difference in what is _idiomatic_ in Kotlin versus Java, and idiomatic Kotlin tends more towards the use of constructors.

In any event, I don't think we want to provide two ways of doing the same thing at this point.

**Comment by asarkar** [comment]
> I don't think we want to provide two ways of doing the same thing

Just to be clear, I wasn't suggesting having two ways, but making the constructor `private` and creating a static factory method in order to be more consistent with the Java generated code. Using the constructors may be your personal preference, but I've not heard that Kotlin prefers constructors over static methods as a general design principle.
