### ISSUE TITLE
Plans for Kotlin Builder DSL?

### ISSUE THREAD

**Issue by yschimke** [grpc/grpc-kotlin#165]
```
Feature.newBuilder().apply { location = request }.build()
```

Replace with

```
Feature.build { 
  location = request 
}
```

**Comment by lowasser** [comment]
This is not a gRPC feature, but a protobuf feature, and is being worked on there. 

> Note: The Kotlin protoc plugin uses the Java protoc plugin behind the scenes to generate message types as Java classes. Generation of Kotlin sources for proto messages is being discussed in protocolbuffers/protobuf#3742.
