### ISSUE TITLE
How to generate kotlin code based on kotlinx.serialization.protobuf

### ISSUE THREAD

**Issue by lz1998** [grpc/grpc-kotlin#181]
With annotation, I think it will be better
```kotlin
@Serializable
@ProtoNumber
```

**Comment by lowasser** [comment]
This is not something we're likely to get to anytime soon, and is arguably a pretty different project.  This project is, for the moment, solely focused on gRPC services defined in `.proto` files.  Kotlin proto serialization is arguably a misnomer -- the proto project is really about the cross-language proto definition, and Kotlin proto serialization is really just about the serialization format.
