### ISSUE TITLE
Possible design flaw with generated code

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-kotlin#182]
Given a proto:
```
rpc Tell(stream Request) returns (Empty) {}
message Empty {}
```
The code generated is roughly as follows:
```
open suspend fun Tell(requests: Flow<Request>): Empty
```

As evident from the return type, this method is meant to be a fire-and-forget, where the client doesn't wait for the server. The server does its thing, and when done, inserts a record in a database that is later looked up by the client. That is all good, but the issue is the suspending function.

According to [Coroutine Context and Scope](https://medium.com/@elizarov/coroutine-context-and-scope-c8b255d59055), launching concurrent work in suspending functions is strongly discouraged.

> If you need to launch a coroutine that keeps running after your function returns, then make your function an extension of `CoroutineScope` or pass `scope: CoroutineScope` as parameter to make your intent clear in your function signature. Do not make these functions suspending:
> Suspending functions, on the other hand, are designed to be non-blocking and should not have side-effects of launching any concurrent work. Suspending functions can and should wait for all their work to complete before returning to the caller.

However, there's no way to not make `Tell` a regular function if extending the coroutine base class. This seems like a fragile assumption been made in the `grpc-kotlin` library not knowing what the user might need to do in their implementation.

**Comment by lowasser** [comment]
This is working as intended, matches the intended gRPC model, and isn't going to change.  Here are a couple reasonable designs for this API, in roughly descending order of my preference:

* `tell` on the server should complete all of the work and then return, and the client should `launch` the RPC asynchronously.  Notably, this means that the client can at least notice if there's an exception by looking at the `Job` from `launch`.  But this, for example, gives the client the flexibility to say, "No, I'm going to wait until the commit is definitely done so I can see if it errors or anything," _or_ to `launch` when it doesn't care.
* `tell` on the server should return as soon as it adds the appropriate request info to a queue being consumed in another `CoroutineScope`.
* `tell` might have a streaming return, which can pass back error messages if necessary but isn't expected to return anything immediately.  (This is admittedly a bit wacky.)

In any event, anything you can do in a normal function, you can do in a suspending function; I'd call this approach _less_ fragile than the alternative.  It might not be good practice to fire-and-forget in a suspending function -- but honestly, I don't think it'd be good practice in a normal function implementing a gRPC method, anyway.

**Comment by asarkar** [comment]
> anything you can do in a normal function, you can do in a suspending function

As I quoted above, the designers of coroutine would disagree. And I also have not seen any design guideline that denounces fire-and-forget in a regular function; after all, that why `launch` exists.
