### ISSUE TITLE
make bindService non-final

### ISSUE THREAD

**Issue by arn95** [grpc/grpc-kotlin#186]
I'm wondering if we could please revert this decision?
https://github.com/grpc/grpc-java/issues/2552

I decided to open a ticket here since I will be using the kotlin generator moving forward.

Having no control over the lifecycle of the service is a bigger UX friction than a problem with X testing framework not being able to mock a function a certain way. You can mock what you want `bindService` to do as its stated in the ticket. How is a problem during testing with mocks a bug? Mocks are notorious for being finicky.

My use case is to invoke some functionality that requires the service to be bound or after `bindService`. Not sure what a workaround for that could be. Any ideas?

**Comment by arn95** [comment]
I also saw this: https://github.com/grpc/grpc-java/issues/4970

Maybe a solution to this could be adding a callback like `onBindService` which is called when `bindService` is done doing its thing. Java 8 has default methods for interfaces. Not sure if grpc is backwards compatible beyond Java 8.

**Comment by lowasser** [comment]
Could you explain in more detail what you mean by "requiring the service to be bound after bindService"?  

You might consider making your own `BindableService` wrapper implementation which calls into the Kotlin implementation's `bindService` and manipulates it accordingly or calls it at the appropriate time.

**Comment by arn95** [comment]
I meant to say functionality that is invoked when bindService is called or more precisely after it's called since you want to call super and then invoke your functionality. 

I will check out what you proposed, I didn't think of it. Sounds reasonable.

**Comment by arn95** [comment]
I looked into what you suggested and wasn't able to come up with something that worked for me. I did however solve the issue I was having by changing the order my services get added to the server since some of my functionality depends on creating a channel to talk to another service.
