### ISSUE TITLE
RouteGuideClient.kt: drop Printer interface

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#19]
@lowasser, I'm trying to keep the tutorial example as simple as possible.

The [RouteGuideServer](https://github.com/grpc/grpc-kotlin/blob/master/examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideServer.kt) simply uses `println()` to generate output

Could we use `println()` in `RouteGuideClient` instead of defining and using the [`Printer` interface](https://github.com/grpc/grpc-kotlin/blob/master/examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideClient.kt#L87-L96)?

```kotlin
  interface Printer {
    companion object {
      val stdout = object : Printer {
        override fun println(str: String) {
          System.out.println(str)
        }
      }
    }
    fun println(str: String)
  }
```

**Comment by lowasser** [comment]
Yes, certainly.  Go for it.

**Comment by chalin** [comment]
Great, thanks!
