### ISSUE TITLE
IDEA: Unresolved reference: GreeterGrpcKt

### ISSUE THREAD

**Issue by hxl-dy** [grpc/grpc-kotlin#214]
grpc-kotlin:v0.2.1 in IDEA:2020.3 on Win10:20.04

https://github.com/grpc/grpc-kotlin/blob/6749f8a8d2a83695fe0e09ef3443a632f3519754/examples/server/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldServer.kt#L48

![image](https://user-images.githubusercontent.com/15082228/101325555-e99c6700-38a6-11eb-9545-f9625979b556.png)

**Comment by jamesward** [comment]
Unfortunately, you have to manually add the generated dirs as source dirs:
https://github.com/google/protobuf-gradle-plugin/issues/109

**Comment by hxl-dy** [comment]
```kotlin
sourceSets {
    val main by getting { }
    main.java.srcDirs("build/generated/source/proto/main/grpc")
    main.java.srcDirs("build/generated/source/proto/main/grpckt")
    main.java.srcDirs("build/generated/source/proto/main/java")
}
```
