### ISSUE TITLE
Provide MyServiceGrpcKt.serviceName

### ISSUE THREAD

**Issue by jachor** [grpc/grpc-kotlin#225]
We right now have `MyServiceGrpcKt.serviceDescriptor`, but sometimes compile-time constant service name is useful. 

Exact case I have is Dagger multi-binding serviceName:String -> grpcService. I can not use `MyServiceGrpcKt.serviceDescriptor.serviceName` as it is not compile-time constraint. Workaround is to use Java gRPC, as it generates `MyServiceGrpc.SERVICE_NAME`. I'd prefer if Kotlin code didn't have to also include Java gRPC stub.

**Comment by bshaffer** [comment]
`SERVICE_NAME` constant has been added in #236

**Comment by Kernald** [comment]
Any idea of when we can expect a release including this?

**Comment by jamesward** [comment]
There is just one other thing I think we need to tackle for a `1.0.1` release.  So hopefully very soon!
