### ISSUE TITLE
in my idea grpc service exception ? thanks

### ISSUE THREAD

**Issue by code33** [grpc/grpc-kotlin#226]
gradle fresh finish then throw this exception , how can i fix it ! thanks a lot!

code in HelloWorldServer.kt this file

this is image 👇 ↓

[image](https://hi.aizhuhotel.com/exception-kotlin.png)

**Comment by jamesward** [comment]
IntelliJ doesn't see the generated sources for some reason. You can find more info about fixing this at: https://github.com/grpc/grpc-kotlin/issues/142#issuecomment-657603225
