### ISSUE TITLE
allOpen KT plugin for Kotlin generated code

### ISSUE THREAD

**Issue by tandel-pratik** [grpc/grpc-kotlin#230]
This might be more of a question but I was curious how I can use the allOpen KT plugin for the Kotlin generated stubs in Bazel. Specifically I want the annotation `io.grpc.kotlin.StubFor` on `HelloServiceCoroutineStub`. I'm using AOP frameworks where to be able to test correctly I need it to be non-final to be mockable.

**Comment by lowasser** [comment]
In general, the intended API for testing gRPC clients in Kotlin -- as in Java -- is to implement the server API, which is not final, and to interact with it via an in-process server.  See https://github.com/grpc/grpc-java/blob/master/examples/src/test/java/io/grpc/examples/helloworld/HelloWorldServerTest.java for an example.

**Comment by xmlking** [comment]
I has been starting the Server as part of unit tests. 
https://github.com/xmlking/micro-apps/blob/develop/apps/account-service/src/test/kotlin/micro/apps/echo/EchoServiceTest.kt
InProcessServerBuilder looks like the better option.
