### ISSUE TITLE
1.0.0 fails unable to fine protoc-gen-grpc-kotlin-1.0.0-windows-x86_64.exe

### ISSUE THREAD

**Issue by bellini-ea** [grpc/grpc-kotlin#233]
Hello,

I am upgrading from 0.1.5 to 1.0.0 and immediately get this failure.  Looking for some guidance around this as maybe this is exposing an issue in my setup or is a known issue?
```
Could not resolve all files for configuration ':api-test-protocol:protobufToolsLocator_grpckt'.
   > Could not find protoc-gen-grpc-kotlin-1.0.0-windows-x86_64.exe (io.grpc:protoc-gen-grpc-kotlin:1.0.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-kotlin/1.0.0/protoc-gen-grpc-kotlin-1.0.0-windows-x86_64.exe
```

**Comment by jamesward** [comment]
Make sure you are using `protobuf-gradle-plugin` `0.8.13` or newer.

**Comment by jamesward** [comment]
Oh and the syntax for using the protoc plugin is slightly different.  See this page for Maven or Gradle instructions:
https://github.com/grpc/grpc-kotlin/blob/master/compiler/README.md

**Comment by Syntey** [comment]
I have a similar problem regarding the jar
```
Execution failed for task ':protos:generateProto'.
> protoc: stdout: . stderr: /home/username/.gradle/caches/modules-2/files-2.1/io.grpc/protoc-gen-grpc-kotlin/1.0.0/d6c8cbe29c60b202165593be5244ce43d37378ac/protoc-gen-grpc-kotlin-1.0.0-jdk7.jar: program not found or is not executable
  Please specify a program using absolute path or make sure the program is available in your PATH system variable
  --grpckt_out: protoc-gen-grpckt: Plugin failed with status code 1.
```
  
I cannot find what I did wrong.

<details>
<summary>build.gradle</summary>

```
plugins {
    id 'java-library'
    id 'kotlin'
    id 'com.google.protobuf'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
}

sourceSets{
    main {
        java {
            srcDirs "${protobuf.generatedFilesBaseDir}/main/grpc"
            srcDirs "${protobuf.generatedFilesBaseDir}/main/grpckt"
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.4.30"
    api 'com.google.protobuf:protobuf-javalite:3.13.0'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.8"
    
    api "io.grpc:grpc-kotlin-stub:1.0.0"

}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.13.0'
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.32.1"
        }
        grpckt {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:1.0.0:jdk7@jar"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                grpc { option 'lite' }
                grpckt { option 'lite' }
            }
        }
    }
}
```
</details>

**Comment by jamesward** [comment]
@Syntey Your problem is different but I believe it might be due to not having `java` on the `PATH` or not having `JAVA_HOME` set.

**Comment by bellini-ea** [comment]
As an update here, I am on protobuf plugin 0.8.15.  As noted above, the way the generateProtoTask is to be used is slightly different from what I had (based on the readme).  I had to change `all().forEach{}` to `ofSourceSet("main).forEach() {}`.  That is the only different that stood out to me.   Below is my protobuf setup in the gradle file (I am using the Kotlin DSL).

That change removes the issue with not able to find `protoc-gen-grpc-kotlin-1.0.0-windows-x86_64.exe`.  However the code breaks now and so I'm working through that to see what's going on.

```
protobuf {
    generatedFilesBaseDir = "${projectDir}/src/generated"
    tasks.clean { delete(generatedFilesBaseDir) }

    protoc {
        // The artifact spec for the Protobuf Compiler
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }

    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java::$grpcVersion"
        }
        id("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:$grpcKotlinVersion"
        }
    }

    generateProtoTasks {
//        all().forEach {
        ofSourceSet("main").forEach {
            // Always delete existing generated code before generating again to avoid conflict
            it.doFirst { delete(generatedFilesBaseDir) }
            it.plugins {
                id("grpc") {}
                id("grpckt") {}
            }
        }
    }
}
```

**Comment by bellini-ea** [comment]
Just following up here with this before closing the ticket.  The main changes to get through the upgrade are:
1. using ofSourceSet("main").forEach  in the generateProtoTasks
2. adding :jdk7@java after the artifact in the plugins section

Now that get things moving again but there are still issues.  The code that built before no longer builds mostly because it can't find files.  So there are more changes hidden here that making this upgrade a pain to figure out.

**Comment by jamesward** [comment]
Thanks for the updates. What are the build errors now?
