### ISSUE TITLE
Add optional fields

### ISSUE THREAD

**Issue by z0mb1ek** [grpc/grpc-kotlin#238]
Now since protobuf [3.15](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) optional is production ready

**Comment by mazuninky** [comment]
I see that a PR #218 with support for optional fields has been merged into master. Do you have any plans to release a new version soon?

**Comment by jamesward** [comment]
I'd like to figure out what to do with https://github.com/grpc/grpc-kotlin/issues/234 then get a new release out.  I'll setup a milestone.

**Comment by jamesward** [comment]
I'm going to close this since #218 was merged. Hopefully we will get a release out very soon.

**Comment by NilMouraa** [comment]
@jamesward, Do you have a forecast for the launch of the [1.1.0](https://github.com/grpc/grpc-kotlin/milestone/7) release?

**Comment by jamesward** [comment]
The `1.1.0` release is out! Check out the changelog for details: https://github.com/grpc/grpc-kotlin/blob/master/CHANGELOG.md
