### ISSUE TITLE
Unable to run installDist for example

### ISSUE THREAD

**Issue by IgorGanapolsky** [grpc/grpc-kotlin#239]
Hello, I am running your example in the `examples` directory.  Upon attempting to execute this command:
`./gradlew installDist`, I get an error:
>  java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x42aeb68d) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x42aeb68d

**Comment by jamesward** [comment]
I don't think we usually run `installDist` on the root project. What subproject are you trying to use? What JDK version are you using?

**Comment by IgorGanapolsky** [comment]
I am following your instructions here: https://grpc.io/docs/platforms/android/kotlin/quickstart/

**Comment by IgorGanapolsky** [comment]
I ran your command.  Here is what came out:
> What went wrong:
Execution failed for task ':stub:compileJava'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x42aeb68d) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x42aeb68d

On my MacBook, the default Java version is openjdk 16.  However, in Android Studio, I use the built-in JDK:
<img width="1258" alt="Screen Shot 2021-03-30 at 12 34 16 PM" src="https://user-images.githubusercontent.com/201209/113024025-483a6900-9154-11eb-8db4-b1346c07185b.png">

**Comment by jamesward** [comment]
It looks like you are using a JDK that is part of Android Studio.  You'll probably need to get a regular JDK like from: https://adoptopenjdk.net/

**Comment by IgorGanapolsky** [comment]
I set it to `/Users/igorganapolsky/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home`.  It still gives the same error.

**Comment by jamesward** [comment]
How are you running the task?  (Command line or from Android Studio?)

**Comment by IgorGanapolsky** [comment]
Terminal inside Android Studio.

**Comment by jamesward** [comment]
Can you verify in that terminal that the right JDK is being used? Maybe with `java -version` or `echo $JAVA_HOME`?

**Comment by IgorGanapolsky** [comment]
Good point!  I changed the JAVA_HOME in my **~/.bash_profile**.  Now it builds.
