### ISSUE TITLE
Why are CoroutineImplBase functions for server streaming non-suspend?

### ISSUE THREAD

**Issue by haithamgabr** [grpc/grpc-kotlin#241]
In a generated XYZGrpcKt.XYZCoroutineImplBase, the functions for server-streaming RPCs are non-suspend, as opposed to unary RPCs. Is there a specific reason for that? Is there a design difference? Is there a difference in how they are being called? 

Any explanation about the difference in how they are called, and how this should reflect in their implementations is highly appreciated.

**Comment by haithamgabr** [comment]
@bshaffer If you can shed some light on the reasoning behind this, it would be greatly appreciated
https://github.com/grpc/grpc-kotlin/blob/master/compiler/src/main/java/io/grpc/kotlin/generator/GrpcCoroutineServerGenerator.kt#L164

Any explanation about what is specific about server streaming in this aspect, and how does this reflect on service implementation differences would really help.

**Comment by mpires** [comment]
My understanding is that it's because server streaming returns a flow, which is only suspendable on `collect` initiated by the client

**Comment by haithamgabr** [comment]
Yes thanks for the reply. I managed, with the help of some friends, to form an understanding of this.
So to close the loop, [this line](https://github.com/grpc/grpc-kotlin/blob/ef06b07a84256a116b16afa2fd3d7aecf4aa402f/stub/src/main/java/io/grpc/kotlin/ServerCalls.kt#L245) is where the flow collection happens, and the framework coroutine context is conserved and propagated to the business logic because the flow code is deferred and only executed at collection.
