### ISSUE TITLE
Non-blocking way to build a struct from JsonObject (in Kotlin serialization)

### ISSUE THREAD

**Issue by keith-miller** [grpc/grpc-kotlin#242]
Hello, I am looking to see if there is a non-blocking way to build a Struct from the serialization JsonObject. I have the following code:

```kotlin
val jsonObject = Json.decodeFromString<JsonObject>("{}")
val structBuilder = Struct.newBuilder()
JsonFormat.parser().merge(jsonObject.toString(), structBuilder)
val struct = structBuilder.build()
```

but the merge call is a blocking one:

![Screen Shot 2021-04-11 at 12 45 50 AM](https://user-images.githubusercontent.com/787338/114296301-6ca11a00-9a5f-11eb-9865-c4097c69ae47.png)

Just wondering if there is any solution besides moving the proto back to a string. Thanks!

**Comment by jamesward** [comment]
It seems that this is due to exceptions under the covers and you can either wrap them or suppress the warning:
https://stackoverflow.com/questions/58680028/how-to-make-inappropriate-blocking-method-call-appropriate

I don't think there is anything we need to change on the grpc-kotlin side of thems.

**Comment by keith-miller** [comment]
Right, I guess my question is that is it possible to build a struct with the Kotlin serialization parser instead of Gson, but this probably isn't the right forum for that question.

**Comment by keith-miller** [comment]
Thanks for the response!

**Comment by jamesward** [comment]
Maybe an admin on this repo (@bshaffer perhaps) can enable discussions? https://docs.github.com/en/discussions/quickstart

**Comment by bshaffer** [comment]
@jamesward done! https://github.com/grpc/grpc-kotlin/discussions

**Comment by keith-miller** [comment]
Perfect, thanks!
