### ISSUE TITLE
Server writes headers immediately on call start, which causes issues with proxy retries

### ISSUE THREAD

**Issue by rwbergstrom** [grpc/grpc-kotlin#272]
Currently the very first thing `ServerCalls.serverCallListener` does is write empty headers back (https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/ServerCalls.kt#L214), before transferring control over to the actual RPC handler.

This causes some problems when used with Envoy-based proxies, since it can no longer perform retries if a failure occurs after the initial headers are written back to the downstream. This was somewhat expected with streaming calls, but was surprising with unary calls - even if a RPC handler immediately writes back a retriable error, Envoy can't do the retry since the headers have already been committed.

Coming from `grpc-java` or KrotoPlus, both of those use the Java API's `StreamObserver`, which defers the `sendHeaders` call until the first message is written back (https://github.com/grpc/grpc-java/blob/v1.38.1/stub/src/main/java/io/grpc/stub/ServerCalls.java#L361). As far as I can tell `grpc-go` behaves similarly as well, deferring the headers as late as possible (https://github.com/grpc/grpc-go/blob/v1.38.0/internal/transport/transport.go#L300) unless the RPC handler explicitly writes them earlier.

To provide a more consistent behaviour compared to other gRPC implementations, is there any reason `grpc-kotlin` can't do the same? Happy submit a PR here, since it looks like a fairly straightforward change.

**Comment by lowasser** [comment]
Happy to accept a PR.

**Comment by rwbergstrom** [comment]
Apologies for the delay, had to sort out the CLA with our legal folks. PR @ #275.

**Comment by ejona86** [comment]
All implementations should really not eagerly send headers by default. This was defined in [the retries gRFC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#when-retries-are-valid):

> gRPC servers should delay the Response-Headers until the first response message or until the application code chooses to send headers. If the application code closes the stream with an error before sending headers or any response messages, gRPC servers should send the error in Trailers-Only.

Since retries are handled by grpc-java, it isn't all that surprising that this would have been overlooked for the Kotlin stub. This sort of thing is rare, so I don't expect such oversights to happen all that frequently.
