### ISSUE TITLE
Support to run on M1

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-kotlin#273]
```
Could not find protoc-gen-grpc-java-1.39.0-osx-aarch_64.exe (io.grpc:protoc-gen-grpc-java:1.39.0)
Could not find protoc-gen-grpc-kotlin-1.1.0-osx-aarch_64.exe (io.grpc:protoc-gen-grpc-kotlin:1.1.0)
```

**Comment by saturnism** [comment]
The first part is here: https://github.com/google/protobuf-gradle-plugin/issues/492
a workaround is to hardcode the the variant to `osx-x86_64`

second part, relevant to `grpc-kotlin`, was a configuration error, which is suppose to use variant `jdk7@jar` that's works w/ any jvm.

```
plugins {
   id("grpc") {
    artifact = "io.grpc:protoc-gen-grpc-java:${Versions.grpcVersion}:osx-x86_64"
  }
  id("grpckt") {
    artifact = "io.grpc:protoc-gen-grpc-kotlin:${Versions.grpcKotlinVersion}:jdk7@jar"
  }
}
```

**Comment by jamesward** [comment]
Since grpc-kotlin no longer distributes exe's, I think the only issue here is with grpc-java.  Maybe I can transfer this over to grpc-java?

**Comment by jeffreychuuu** [comment]
You may simply add `:osx-x86_64` behind if you are using m1 mac

**Comment by martintreurnicht** [comment]
Issue has been resolve since https://github.com/grpc/grpc-java/releases/tag/v1.42.1, but https://github.com/grpc/grpc-java/releases/tag/v1.43.0 i believe now have true native support

**Comment by jamesward** [comment]
Looks like we should be good, assuming we can work with those versions of grpc-java.  Closing but feel free to re-open if there are still issues.

**Comment by sreid8** [comment]
I think this issue needs to be reopened. I'm seeing the same error with grpc-java 1.54.0 and grpc-kotlin 1.3.0:

```kotlin
plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.54.0"
        }
        id("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:1.30.0"
        }
    }
```

The build error is:
```
Execution failed for task ':generateProto'.
> Could not resolve all files for configuration ':protobufToolsLocator_grpckt'.
   > Could not find protoc-gen-grpc-kotlin-1.30.0-osx-aarch_64.exe (io.grpc:protoc-gen-grpc-kotlin:1.30.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-kotlin/1.30.0/protoc-gen-grpc-kotlin-1.30.0-osx-aarch_64.exe
```

Am I doing something wrong or does this actually not work on Apple Silicon machines?

**Comment by jamesward** [comment]
You need to include the plugin like so:
'''
id("grpckt") {
    artifact = "io.grpc:protoc-gen-grpc-kotlin:YOUR_GRPC_KOTLIN_VERSION:jdk8@jar"
}
'''
