### ISSUE TITLE
Failed to generate proper kotlin file for a service using protoc using protoc-gen-grpckt or protoc-gen-android plugins

### ISSUE THREAD

**Issue by ysweid** [grpc/grpc-kotlin#286]
### First Trial (using protoc-gen-android):

I have a protobuf file that declares the following options:

```proto
syntax = "proto3";

package account;

option java_multiple_files = true;
option java_package = "com.global.projectblue.android.network.account";
option java_outer_classname = "AccountOuterProto";

service AccountService {
    rpc GetSession(GetSessionInput) returns (GetSessionOutput) {}
    .......
}
```

Using the following command to generate kotlin code:

```shell
$ echo "#!/usr/bin/env sh\n java -jar bin/protoc-gen-grpc-kotlin-1.1.0-jdk7.jar" > $(PWD)/bin/protoc-gen-kotlin.sh
$ chmod +x $(PWD)/bin/protoc-gen-kotlin.sh
$ protoc -I=. --plugin=protoc-gen-android=$(PWD)/bin/protoc-gen-kotlin.sh --android_out=bin/android/service service/account/account.proto
```

The result is one generated file called `AccountOuterProtoGrpcKt.kt` that's using missing class called `AccountServiceGrpc` that I didn't find in the source code.

```kotlin
object AccountServiceGrpcKt {
  const val SERVICE_NAME: String = AccountServiceGrpc.SERVICE_NAME

  @JvmStatic
  val serviceDescriptor: ServiceDescriptor
    get() = AccountServiceGrpc.getServiceDescriptor()
   ................
```

### Second Trial (using protoc-gen-grpckt):

For the same protobuf, I changed the command to be the following:

```shell
$ echo "#!/usr/bin/env sh\n java -jar bin/protoc-gen-grpc-kotlin-1.1.0-jdk7.jar" > $(PWD)/bin/protoc-gen-kotlin.sh
$ chmod +x $(PWD)/bin/protoc-gen-kotlin.sh
$ protoc -I=. --plugin=protoc-gen-grpckt=$(PWD)/bin/protoc-gen-kotlin.sh --grpckt_out=bin/android/service --proto_path=service/account/ service/account/account.proto
```

And I ended up with the same result. The file `AccountOuterProtoGrpcKt.kt` generated but without `AccountServiceGrpc` inside.

```
$ protoc --version
libprotoc 3.17.3
```

Anything I am missing?

**Comment by ysweid** [comment]
Anyone !?

**Comment by bjoernmayer** [comment]
Hey @ysweid ,
AFAIK grpcKotlin is built on top of grpc java. So you need to generate both java and kotlin.

**Comment by udishkumar** [comment]
Hello, Is this issue resolved? If yes, can anyone tell me how did you guys resolve it? I am generating Java and Kotlin both files. But still issue persists.
