### ISSUE TITLE
Expose a callback to eagerly send headers?

### ISSUE THREAD

**Issue by andrewparmet** [grpc/grpc-kotlin#291]
[Now that headers are not sent immediately](https://github.com/grpc/grpc-kotlin/pull/275), I'd like to have a way to trigger headers before I actually have the first response message ready for a client. In grpc-java the usual technique is to cast the `StreamObserver` to a `ServerCallStreamObserver` (or a `ClientCallStreamObserver` when client-side) for these cases, as discussed in https://github.com/grpc/grpc-java/issues/8434.

Could it similarly make sense to expose a custom `Flow` implementation to expose this kind of behavior?

**Comment by ejona86** [comment]
We recently realized we _don't_ want such an API for unary responses for gRPC Java. See https://github.com/grpc/grpc-java/issues/8434#issuecomment-955100019 . For streaming responses it is no problem.

We basically want to keep the door open for batching response headers with the message and trailers. I do recognize that Kotlin's behavior here may have cracked open the door and we may need to keep compatibility options open.

**Comment by andrewparmet** [comment]
We're no longer in need of this API. Thanks all.
