### ISSUE TITLE
Publish grpc-kotlin-stub-lite 1.2.0

### ISSUE THREAD

**Issue by jagobagascon** [grpc/grpc-kotlin#314]
Hello! I'm trying to use `grpc-kotlin-stub-lite:v1.2.0` but [it is missing from maven central](https://mvnrepository.com/artifact/io.grpc/grpc-kotlin-stub-lite) (v1.1.0 is missing too).

I've seen there's an issue to automate the releases (#313) but I'm afraid that may take some time. **Is it possible you could publish the lite version of the latest release to maven central?**

**Comment by jamesward** [comment]
That artifact went away in 1.1.0 - see:
https://github.com/grpc/grpc-kotlin/blob/master/CHANGELOG.md#110
https://github.com/grpc/grpc-kotlin/issues/234

Let me know if you have any issues with that change.

**Comment by jagobagascon** [comment]
Oops, I missed that. That works for me, thank for the quick response!
