### ISSUE TITLE
proto generation for kotlin using bazel

### ISSUE THREAD

**Issue by aryeh-looker** [grpc/grpc-kotlin#341]
would be awesome to have in the docs

**Comment by aryeh-looker** [comment]
cc/ @aragos

**Comment by aryeh-looker** [comment]
Open question for me -- I think @aragos is the domain expert here:

I can bring in this repo in my `WORKSPACE` file with something like this:

```
rules_kotlin_version = "1.5.0"
rules_kotlin_sha = "12d22a3d9cbcf00f2e2d8f0683ba87d3823cb8c7f6837568dd7e48846e023307"
http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = rules_kotlin_sha,
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % rules_kotlin_version],
)
```

From there, I can (attempt) to use the rule like this:

```
load("@io_grpc_grpc_java//:java_grpc_library.bzl", "java_grpc_library")
```

When I do that, though, that needs transitive deps that are not furnished by my `WORKSPACE`. 

It's not clear from the `WORKSPACE` file in this repo what the minimal set of deps are -- would probably be really helpful for folks.

**Comment by aragos** [comment]
You should be able to use [repositories.bzl](https://github.com/grpc/grpc-kotlin/blob/master/repositories.bzl) to load all dependencies of this bazel repo.
