### ISSUE TITLE
When request is converted to String, a line break character is always appended

### ISSUE THREAD

**Issue by michaelfyc** [grpc/grpc-kotlin#345]
My  Kotlin version: 1.7.0
My grpc-Kotlin version: 1.3.0 
My grpc version: 1.47.0
My protobuf version: 3.21.1

My protobuf file:
```protobuf
syntax = "proto3";
package com.grpc.demo;
option java_multiple_files = true;

message HelloRequest{
  string username  = 1;
}

message HelloResponse{
  string messageText = 1;
}

service HelloService{
  rpc sayHello(HelloRequest) returns (HelloResponse);
}
```

My server side code:
``` kotlin
private val logger = KotlinLogging.logger{}
class HelloServiceImpl : HelloServiceGrpcKt.HelloServiceCoroutineImplBase() {
    override suspend fun sayHello(request: HelloRequest): HelloResponse {
        logger.info("HelloRequest{$request}")
        val username = request.username
        return HelloResponse.newBuilder().setMessageText("Hello, $username!").build();
    }
}
```
When client side passes 'John' as username, the console from server side always print 
```
HelloRequest{John
}
```
A line break `\n`  is appended when request is converted to String by `toString` method, and this forces me to trim manually every time in advance. Is this an expected behavior? If so, is there any good practice for logging coming requests?

**Comment by jamesward** [comment]
I'm pretty sure the printing behavior comes from the underlying `protobuf-java` library:
https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/TextFormat.java

This would have to be fixed over there.
