### ISSUE TITLE
Access current RPC's CoroutineScope in Server Streaming RPC

### ISSUE THREAD

**Issue by trietsch** [grpc/grpc-kotlin#372]
I've got a Server Streaming RPC, and our APIs heavily depend on an RPC's CoroutineScope and the attached CoroutineContext. As mentioned in https://github.com/grpc/grpc-kotlin/issues/241, the function is not suspendable, which leads to no access to the CoroutineContext.

Two questions:
1. Is there any objection to make server streaming RPCs suspendable?
2. If there are objections, is there a way to access the coroutine that is embedded in the `GrpcContextElement`, which in turn contains a `CombinedContext`? It's impossible to use the `Coroutine::get` function, as that uses [reference equality](https://stackoverflow.com/a/57099181), and the [actual instance is marked as `internal`](https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/CoroutineContextServerInterceptor.kt#L21). Image below shows that the contents that are extracted from the gRPC Request Metadata and put in the RPC's CoroutineContext are present:
![image](https://user-images.githubusercontent.com/22979744/207320987-861c2d3f-e7c6-49b7-8509-eebfd4d80cb8.png)

Any other approaches I could use to access the RPC's CoroutineContext for a Server Streaming RPC?

**Comment by trietsch** [comment]
It's possible to access the internal `COROUTINE_CONTEXT_KEY` and do a `key.get(GrpcContext.current())`, after which it's possible to retrieve the individual contents. Though my preference is not to use Kotlin Reflect at all here.

Would it be an idea to add a public `fun <T> getGrpcContextElement(key: CoroutineContext.Key<T>)` in the companion object, so that it would be possible to do `CoroutineContextServerInterceptor.getGrpcContextElement(ExternalUserContext)` in the image above?

**Comment by lowasser** [comment]
Functions that return Flows -- such as the server streaming RPC APIs -- should not suspend.  Instead, the appropriate idiom is to do something like:

```
fun doStreamingRpc(request: Request): Flow<Response> = flow {
  coroutineScope {
    ...logic that uses a CoroutineScope and perhaps calls emitAll on another flow...
  }
}
```

**Comment by trietsch** [comment]
@lowasser ah, that was the information that I was missing! Thanks for the quick response. I could do with an extra course on coroutines 😄.
