### ISSUE TITLE
Library bundles Kotlin runtime

### ISSUE THREAD

**Issue by andrewparmet** [grpc/grpc-kotlin#38]
When I attempt to build the examples project Gradle warns:
```
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
w: /Users/andrewparmet/.m2/repository/io/grpc/grpc-kotlin/0.1/grpc-kotlin-0.1.jar: Library has Kotlin runtime bundled into it
```

This causes issues when I use grpc-kotlin as a dependency in a prototype project of my own with `kotlinOptions.allWarningsAsErrors = true`.

When I tried to move the kotlin-coroutines and kotlin-reflect dependencies down from `compile` to `runtime`, naturally the plugin fails to run:
```
protoc: stdout: . stderr: Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/coroutines/flow/Flow
```
Is there a way around this? I can ignore the warning with `-Xskip-runtime-version-check` but that's not a great long-term solution.

**Comment by andrewparmet** [comment]
I'm having another issue which I think is related: when I depend on grpc-kotlin in my application, I get an Android version of Guava on my classpath which prevents me from using methods like Stopwatch.elapsed().

Looks like the jar task assembles a fat jar? That might be necessary to run the plugin, but maybe a different jar can be published for the runtime. We had to do something similar for [protokt](https://github.com/open-toast/protokt).

**Comment by andrewparmet** [comment]
Based on that theory I made a quick and dirty fix that appears to have done the trick: https://github.com/andrewparmet/grpc-kotlin/commit/4d390964cb69410d10c6f3da6017d972fd44f8b5

**Comment by aparmet-toast** [comment]
Looks like https://github.com/grpc/grpc-kotlin/pull/40 fixes this?

**Comment by andrewparmet** [comment]
Looks like #40 fixes this?
