### ISSUE TITLE
why download jdk?

### ISSUE THREAD

**Issue by keyiis** [grpc/grpc-kotlin#381]
I already install jdk and set JAVA_HOME,but still download jdk
<img width="859" alt="1676200268099" src="https://user-images.githubusercontent.com/7766085/218307805-1de962a5-a28d-4e1e-9176-a1289a9818a7.png">

**Comment by jamesward** [comment]
The project uses Gradle Toolchains which makes it easy to control the JDK version.

**Comment by keyiis** [comment]
@jamesward Can i use jdk 17? I changed 11 to 17 in every build.gradle.kts.
<img width="431" alt="1676208420415" src="https://user-images.githubusercontent.com/7766085/218313835-36ded6ad-e4bd-44ba-9765-364bd42ae587.png">

**Comment by keyiis** [comment]
It can build successful,but I don't know it maybe has another problem.
<img width="498" alt="1676208723421" src="https://user-images.githubusercontent.com/7766085/218314063-5f149e8f-0786-46df-b9b4-264413516e78.png">

**Comment by jamesward** [comment]
Yes, changing the toolchain to JDK 17 should work and should be used for compilation.  Is there something that isn't working with that?
