### ISSUE TITLE
--grpc-kotlin_out: protoc-gen-grpc-kotlin: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by fury-r** [grpc/grpc-kotlin#386]
**Command i ran**

 protoc --proto_path=../protobuf     --plugin=protoc-gen-grpc-kotlin=C:/Jars/protoc-gen-grpc-kotlin-1.3.0-jdk8.jar  --kotlin_out=./app/src/main/java   --java_out=./app/src/main/java     --grpc-kotlin_out=./app/src/main/java     ../protobuf/middleware/middleware.proto

output
--grpc-kotlin_out: protoc-gen-grpc-kotlin: %1 is not a valid Win32 application.

It works fine if i don't add --grpc-kotlin_out

Windows:11

**Comment by jamesward** [comment]
The jar isn't executable directly. So I think you'll have to create a shell script file that runs the `java -jar` command.

**Comment by fury-r** [comment]
`protoc --proto_path=../protobuf     --plugin=protoc-gen-grpc-kotlin=run.sh  --kotlin_out=./app/src/main/java   --java_out=./app/src/main/java     --grpc-kotlin_out=./app/src/main/java     ../protobuf/middleware/middleware.proto`


**run.sh**
`java -jar C:/Jars/protoc-gen-grpc-kotlin-1.3.0-jdk8.jar`

**Comment by fury-r** [comment]
@jamesward

**Comment by jamesward** [comment]
Can you try the instructions at: https://github.com/grpc/grpc-kotlin/blob/master/compiler/README.md#manual-protoc-usage

Let me know how that goes.

**Comment by fury-r** [comment]
### proto file

```
syntax="proto3";

package com.middleware;
option java_multiple_files = true;
option java_outer_classname = "Middlewarec";
service Middleware {
    rpc Ping(PingRequest) returns (PingResponse);
 
}

message PingRequest {
    string message = 1;
}
message PingResponse {
    string message = 1;
}
```
### for generating the types
  protoc --proto_path=../protobuf     --plugin=protoc-gen-grpc-kotlin=C:/Jars/protoc-gen-grpc-kotlin-1.3.0-jdk8.jar  --kotlin_out=./app/src/main/java   --java_out=./app/src/main/java ../protobuf/middleware/middleware.proto

### for generating grpc
sudo protoc --plugin=protoc-gen-grpckt=script.sh   --grpckt_out="./app/src/main/java" --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"

This command worked

### MiddlewareGrpcKt.kt
_Unresolved reference: MiddlewareGrpc_
`import com.middleware.MiddlewareGrpc.getServiceDescriptor`


For Some reason its not generating  MiddlewareGrpc.java file

**Comment by fury-r** [comment]
### Commands executed
_proto.sh_

```
sudo protoc --plugin=protoc-gen-kotlin=../../Downloads/grpc/compiler/build/install/compiler/bin/compiler    --kotlin_out=./app/src/main/java --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"
sudo protoc --plugin=protoc-gen-grpc-kotlin=../../Downloads/grpc/compiler/build/install/compiler/bin/compiler   --grpc-kotlin_out="./app/src/main/java"  --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"
sudo protoc --plugin=protoc-gen-java=../../Downloads/grpc/compiler/build/install/compiler/bin/compiler    --java_out=./app/src/main/java --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"
sudo protoc --plugin=protoc-gen-grpc-java=../../Downloads/grpc/compiler/build/install/compiler/bin/compiler   --grpc-java_out="./app/src/main/java"  --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"
```

Check this video to see the output
[Video](https://drive.google.com/file/d/1CbUf4-ylImxvONFUpXMI5wdV-psKR4Kv/view?usp=sharing)

@jamesward

**Comment by jamesward** [comment]
I think that you almost got it. For the `protoc-gen-java` and `protoc-gen-grpc-java` plugin you need to point to the protoc-java plugin. And for `gen-kotlin` and `protoc-gen-grpc-kotlin` you need to point to the protoc-kotlin plugin.

**Comment by fury-r** [comment]
Can you provide me the link to the plugs  ` protoc-gen-java`  and  `protoc-gen-grpc-java`

**Comment by jamesward** [comment]
Latest is here: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.56.0/

**Comment by fury-r** [comment]
Got it working!

```
 protoc --proto_path=../protobuf     --plugin=protoc-gen-kotlin=./script.sh --kotlin_out=./app/src/main/java   --java_out=./app/src/main/java    ../protobuf/middleware/middleware.proto
sudo protoc --plugin=protoc-gen-grpc-kotlin=../../Downloads/grpc/compiler/build/install/compiler/bin/compiler   --grpc-kotlin_out="./app/src/main/java"  --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"
sudo protoc --plugin=protoc-gen-java=../../Downloads/grpc/compiler/build/install/compiler/bin/compiler    --java_out=./app/src/main/java --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"
# sudo protoc --plugin=protoc-gen-grpc-java=./protoc-gen-grpc-java-1.56.0-linux-aarch_64.exe  --grpc-java_out="./app/src/main/java"  --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"
sudo protoc --plugin=protoc-gen-grpc-java=./protoc-gen-grpc-java-1.56.0-windows-x86_64.exe  --grpc-java_out="./app/src/main/java"  --proto_path="../protobuf" "../protobuf/middleware/middleware.proto"

```
