### ISSUE TITLE
Explicitly target some version of Java

### ISSUE THREAD

**Issue by andrewparmet** [grpc/grpc-kotlin#39]
When built with Java 11, the Gradle module metadata published alongside the pom requires any downstream library to use Java 11. If a downstream library wants to target Java 8, Gradle complains:
```
- Variant 'runtimeElements' capability io.grpc:grpc-kotlin:0.1:
    - Incompatible attribute:
        - Required org.gradle.jvm.version '8' and found incompatible value '11'.
```

I was able to fix this locally with the classic:
```groovy
compileJava {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}
```

Ideally I can target Android API 19+, so 1.8 would be ideal.

**Comment by chalin** [comment]
Thoughts @lowasser @bshaffer?

**Comment by lowasser** [comment]
Targeting Java 8 sounds just fine.

**Comment by chalin** [comment]
Have this been addressed @bshaffer @lowasser?

**Comment by dwiner** [comment]
This is being addressed in https://github.com/grpc/grpc-kotlin/issues/84.
