### ISSUE TITLE
kotlin libs should use implementation as oppose to compile?

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-kotlin#43]
e.g., https://github.com/Kotlin/kotlinx.coroutines#gradle

**Comment by bshaffer** [comment]
I use compile for the protoc plugin, and switching to implementation breaks it (they are only collected into the fat jar with compile)

**Comment by chalin** [comment]
@bshaffer - is this still relevant given #53?

**Comment by saturnism** [comment]
protoc and the stubs are different.

stub shouldn't have transitive dependencies because that the user will have to pull in those dependencies.

for proto-gen-kotlin, it doesn't matter as much as long as the final binary is shaded and runs. the correct scope for proto gen koltin, if shaded, is  still still scope `runtime` or `provided` depending on the shading rule.

**Comment by bshaffer** [comment]
Fixed in https://github.com/grpc/grpc-kotlin/pull/56
