### ISSUE TITLE
Readme Gradle Build

### ISSUE THREAD

**Issue by zabakala** [grpc/grpc-kotlin#489]
Hi guys. Trying to follow the docs here https://github.com/grpc/grpc-kotlin/blob/master/compiler/README.md to properly setup  the build.gradle.kts file. Your docs state the following design (attachment 1). But the 1:1 copy inside my IntelliJ IDE has unresolved references (id, artifact) highlighted in red (attachment 2). Would you point me in the right direction?

I have the following implementations:
```
plugins {
    ...
    id("com.google.protobuf") version "0.9.4"
    ...
}

implementation("io.grpc:grpc-protobuf:1.60.0")
implementation("io.grpc:grpc-stub:1.60.0")
implementation("io.grpc:grpc-netty:1.60.0")
implementation("io.grpc:grpc-all:1.60.0")
implementation("io.grpc:grpc-kotlin-stub:1.4.1")
implementation("io.grpc:protoc-gen-grpc-kotlin:1.4.1")
```

![pic1](https://github.com/grpc/grpc-kotlin/assets/6930312/d3bfe3d2-cb65-4f43-ab89-3a82d13d5563)
![pic2](https://github.com/grpc/grpc-kotlin/assets/6930312/5c1c7c3e-4165-4cec-b972-5afd3fa326e1)

**Comment by jamesward** [comment]
I think I need to update that doc. Some of the syntax has changed. See this:

https://github.com/grpc/grpc-kotlin/blob/master/examples/stub/build.gradle.kts

Note the `create` calls instead. I'll try to get that doc updated today.
