### ISSUE TITLE
Publish API reference to gh-pages

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#5]
This issue is to ensure that we don't forget to a least manually publish a first version. Ideally we should automate the process to the extent possible (e.g., at least the API doc generation part, maybe leaving the actual merging into gh-pages as a manual step). /cc @dwiner

Depends on #4.

**Comment by chalin** [comment]
@bshaffer @lowasser - if you setup the doc generation, I don't mind taking care of "publishing" to gh-pages.

**Comment by bshaffer** [comment]
@chalin Louis added `Dokka` integration, so you may be good to go

**Comment by chalin** [comment]
Done: https://grpc.github.io/grpc-kotlin/grpc-kotlin/
