### ISSUE TITLE
 How to intercept all requests?

### ISSUE THREAD

**Issue by AliceCarroll239** [grpc/grpc-kotlin#508]
Hello, 
I'm trying to write a mock service that can respond to those requests for which ImplBase is not generated.
The problem is that such requests are not processed in the ServerInterceptor / interceptCall and an UNIMPLEMENTED error is thrown. 

Is it possible to intercept all requests so that I can work with them?

For example:
I create a server with proto 

`service TestService {
  rpc Hello (HelloRequest) returns (HelloReply);
}`

and with interceptor 

`override fun <ReqT : Any, RespT : Any> interceptCall(
        p0: ServerCall<ReqT, RespT>?,
        p1: io.grpc.Metadata?,
        p2: ServerCallHandler<ReqT, RespT>?
    ): ServerCall.Listener<ReqT> {
        return p2!!.startCall(StatusExceptionHandlingServerCall(p0), p1)
    }`

then I try to execute the request 

`service TestService {
  rpc HelloNew (HelloRequest) returns (HelloReply);
}`

and the server bypasses the interceptor and immediately returns an error UNIMPLEMENTED

**Comment by lowasser** [comment]
I recommend asking the https://github.com/grpc/grpc-java repository about this, as gRPC-Kotlin doesn't add any new features in this area.
