### ISSUE TITLE
编译proto文件生成的类报错，Unresolved reference: HelloRequest

### ISSUE THREAD

**Issue by AngelRiven** [grpc/grpc-kotlin#512]
你好，你能帮我解决下面的问题吗，编译生成的代码文件Unresolved reference: HelloRequest。这只是其中一个错误，其他的message 也找不到。

下面是protobuf  配置
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }

    plugins {
        create("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }
        create("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:${grpcKotlinVersion}:jdk8@jar"
        }
    }

    generateProtoTasks {
        all().forEach {
            it.plugins {
                create("grpc")
                create("grpckt")
            }
            it.builtins {
                create("kotlin")
            }
        }
    }
}
```

这是proto文件
```
syntax = "proto3";

package helloworld;

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello(HelloRequest) returns (HelloReply) {}

  // Sends a greeting to a group
  rpc ClientStreamSayHello(stream HelloRequest) returns (HelloReply) {}

  // Sends a number of hellos
  rpc ServerStreamSayHello(MultiHelloRequest) returns (stream HelloReply) {}

  // Sends interactive hellos
  rpc BidiStreamSayHello(stream HelloRequest) returns (stream HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

message MultiHelloRequest {
  repeated string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```

下面是结果：

<img width="400" alt="5545e2db9dfe76789d9a2191f2698d5" src="https://github.com/grpc/grpc-kotlin/assets/20040783/b042ba90-4d2a-46a8-b153-59075a806a3b">

**Comment by AngelRiven** [comment]
我该如何解决这个问题？

**Comment by AngelRiven** [comment]
下面是完整的build.gradle.kts 文件内容
`
import com.google.protobuf.gradle.proto

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.protobuf") version "0.9.1" // 添加protobuf
    id("kotlin-android")
    id("kotlin-parcelize")
    id("kotlin-kapt")
}

val coroutinesVersion = project.property("coroutines_version")
val krotoplusVersion = project.property("krotoplus_version")
val protobufVersion = project.property("protobuf_version")
val grpcVersion = project.property("grpc_version")
val grpcKotlinVersion = project.property("grpc_kotlin_version")

android {
    namespace = "com.airdoc.healthstation"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.airdoc.healthstation"
        minSdk = 29
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += listOf(
            "-Xuse-experimental=kotlinx.coroutines.ObsoleteCoroutinesApi"
        )
    }
    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }
    buildFeatures {
        viewBinding = true
    }

}

dependencies {

    implementation("androidx.core:core-ktx:1.10.1")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.9.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")

    implementation("com.airdoc.component:common:0.1.3-SNAPSHOT")

    //gRPC
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")

    implementation("com.google.protobuf:protobuf-java:$protobufVersion")
    implementation("com.google.protobuf:protobuf-java-util:$protobufVersion")
    implementation("com.google.protobuf:protobuf-kotlin:$protobufVersion")

    implementation("io.grpc:grpc-protobuf:$grpcVersion")
    implementation("io.grpc:grpc-stub:$grpcVersion")
    implementation("io.grpc:grpc-netty:$grpcVersion")
    implementation("io.grpc:grpc-kotlin-stub:$grpcKotlinVersion")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }

    plugins {
        create("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }
        create("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:${grpcKotlinVersion}:jdk8@jar"
        }
    }

    generateProtoTasks {
        all().forEach {
            it.plugins {
                create("grpc")
                create("grpckt")
            }
            it.builtins {
                create("kotlin")
            }
        }
    }
}
`

**Comment by jamesward** [comment]
Does it work from Gradle and not IntelliJ?

**Comment by AngelRiven** [comment]
> Does it work from Gradle and not IntelliJ?它是从Gradle而不是IntelliJ工作的吗？

是的

**Comment by AngelRiven** [comment]
> Does it work from Gradle and not IntelliJ?它是从Gradle而不是IntelliJ工作的吗？

我把protobuf配置修改成下面这样，增加了java代码的生成，最终编译通过了。这个是必须要生成java代码的吗？

```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }

    plugins {
        create("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }
        create("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:${grpcKotlinVersion}:jdk8@jar"
        }
        create("java"){
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }
    }

    generateProtoTasks {
        all().forEach {
            it.plugins {
                create("grpc"){
                    option("lite")
                }
                create("grpckt"){
                    option("lite")
                }
                create("java"){
                    option("lite")
                }
            }
            it.builtins {
                create("kotlin"){
                    option("lite")
                }
            }
        }
    }
}
```

**Comment by jamesward** [comment]
I believe that the Gradle Protobuf plugin is automatically adding the Java code gen based on something in the project configuration.  In Android projects it doesn't see the configuration so you have to add it manually like in: https://github.com/grpc/grpc-kotlin/blob/master/examples/stub-android/build.gradle.kts
