### ISSUE TITLE
Automate Gradle publish

### ISSUE THREAD

**Issue by jamesward** [grpc/grpc-kotlin#54]

**Comment by bshaffer** [comment]
We did this!

**Comment by jamesward** [comment]
Did we?  I thought you ended up doing `0.1.1` with manual uploads.

**Comment by bshaffer** [comment]
I misunderstood this to mean make available as a package in Gradle.

**Comment by jamesward** [comment]
Yeah, my title is very non-descriptive. :(

So putting this here for future reference... We want to do the Maven Central staging using `gradle publish`.

**Comment by Bleoo** [comment]
hi, I wrote it according to the example of gradle, but it was still wrong
![image](https://user-images.githubusercontent.com/11569795/80477139-06220980-897e-11ea-8105-4f394262e828.png)

**Comment by bshaffer** [comment]
This may be useful also: https://help.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-gradle
