### ISSUE TITLE
Incompatible with latest v26 Protocol Buffers (GeneratedMessageV3 removal)

### ISSUE THREAD

**Issue by dennisameling** [grpc/grpc-kotlin#593]
Protocol Buffers v26.0 [was released three weeks ago](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0).

One of the breaking changes is this one:

> [Java] The base class for generated messages will be GeneratedMessage, not GeneratedMessageV3.

This library doesn't seem to be compatible anymore now. For example, this PR is broken: https://github.com/grpc/grpc-kotlin/pull/588

```
    e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
        class io.grpc.examples.routeguide.Feature, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.animals.BaaReply.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.animals.BarkReply.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.animals.OinkReply.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.helloworld.HelloReply.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.helloworld.HelloRequest.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.routeguide.FeatureDatabase.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.routeguide.Feature.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.routeguide.Point.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.routeguide.Rectangle.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.routeguide.RouteNote.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.routeguide.RouteSummary.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.animals.BaaReply, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.animals.BaaRequest, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.animals.BaaRequest.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.animals.BarkReply, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.animals.BarkRequest, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.animals.BarkRequest.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.animals.OinkReply, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.animals.OinkRequest, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.animals.OinkRequest.Builder, unresolved supertypes: Builder<Builder>
        class io.grpc.examples.helloworld.HelloReply, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.helloworld.HelloRequest, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.routeguide.FeatureDatabase, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.routeguide.Point, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.routeguide.Rectangle, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.routeguide.RouteNote, unresolved supertypes: GeneratedMessageV3
        class io.grpc.examples.routeguide.RouteSummary, unresolved supertypes: GeneratedMessageV3
```

Is there anything we can do to help make it compatible? Thanks!

**Comment by dennisameling** [comment]
Turns out there have been [75 commits to the `master` branch](https://github.com/grpc/grpc-kotlin/compare/v1.4.1...master) since the latest [1.4.1 release on December 14th, 2023](https://github.com/grpc/grpc-kotlin/releases/tag/v1.4.1). One of them is [this one](https://github.com/grpc/grpc-kotlin/commit/8429b87562d0f5e3921f0d1abeaa4e54742a6950), which might (at least partially) fix these version mismatches.

@jamesward would you be able to release a new version with the latest changes from the `master` branch? We'd like to try and see if that resolves the issues for us. Thanks! 😊

**Comment by jamesward** [comment]
Hi @dennisameling, unfortunately I'm no longer working at Google so someone else will need to roll the release.  Sorry!

**Comment by westito** [comment]
There is somebody at Google that can release a new version?

**Comment by jamesward** [comment]
@lowasser should be able to.  Instructions are at:
https://github.com/grpc/grpc-kotlin/blob/master/BUILDING.md#releasing

**Comment by jasonab** [comment]
this problem appears to have been fixed on the Java side

**Comment by dennisameling** [comment]
This indeed seems to be an [issue](https://github.com/grpc/grpc-java/issues/11015) with `grpc-java` (related to the Protobuf upgrade) and not this particular library. A partial fix is already in place, with [more fixes coming soon](https://github.com/protocolbuffers/protobuf/issues/17247#issuecomment-2200422299). I'm going to close this issue now.
