### ISSUE TITLE
Dispatchers.IO Coroutines Example

### ISSUE THREAD

**Issue by gary-lo** [grpc/grpc-kotlin#60]
In the context of a gRPC server. I'm wondering if we could get some guidance around, perhaps in an example, of how best to handle long-running blocking logic (e.g. blocking upstream request) using coroutine.

In particular keen to know, for example a gRPC call upstream request, is the recommended way of making way of running long-running requests using `withContext(Dispatchers.IO)` or is this somewhat irrelevant because the server is already optimized for coroutines. More broadly, how do the servers thread pools relate to the coroutines on the gRPC server?
```
    override suspend fun blockingHello(request: HelloRequest): HelloReply {
        return mockBlockingApiCall(request)
    }

    private suspend fun mockBlockingApiCall(request: HelloRequest): HelloReply = withContext(Dispatchers.IO) {
        delay(3_000) // emulate long running API call
        buildReply(toMessage(request.name))
    }
```

https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/AbstractCoroutineServerImpl.kt#L32

**Comment by jeffzoch** [comment]
Tacking on - curious how previous advice around grpc-java to use a different executor / threadpool than the default one comes into play here. It would be ideal if we could get a few suggestions around configuring grpc-kotlin performance based on some different use-cases

**Comment by gary-lo** [comment]
@jeffzoch in the meantime there's a great conversation here around how they are looking to handle it within Netty/Armeria https://github.com/line/armeria/pull/2669

**Comment by lowasser** [comment]
For servers, I don't think there is any real difference between what you should do for gRPC and what you should do for any coroutine?  If some dispatcher would be more appropriate to run a particular operation, use `withContext(thatDispatcher)` as normal.

**Comment by gary-lo** [comment]
Thanks for the reply @lowasser so to be explicit the following way to call upstream is fine? :
```
class FooImpl(
    private val serviceStub: BarServiceGrpc.BarServiceBlockingStub
) : BarServiceGrpcKt.BarServiceCoroutineImplBase() {

    override suspend fun getEntity(request: Foo.FooRequest): Foo.Entity {
        return withContext(Dispatchers.IO) {
            serviceStub.getBooze(request)
        }
    }
}
```

**Comment by lowasser** [comment]
The projects I work with ban the use of any of the `Dispatchers` constants, so I'm not actually certain, but I believe you would probably prefer to use `IO`, which is intended for use when some of the coroutines might effectively block frequently.

**Comment by gary-lo** [comment]
Thanks @lowasse. 

When you say it's banned. You mean, there's an internal alternative `CoroutineContext` to Dispatchers? 
Or there's a complete alternative in general? 

I'm curious to understand why it's banned?

**Comment by lowasser** [comment]
We require that dispatchers be injected, and generally that they come from `Executor.asCoroutineDispatcher()`.  VM-wide shared thread pools like `Dispatchers.IO` require an entire app and all of its dependencies to use the same pool and the same number of threads comfortably, and don't play nicely with every configuration setup.

**Comment by briangriffeyudemy** [comment]
Semi-related question here: Is there a way to have the grpc server initially dispatch requests onto a threadpool other than Dispatchers.Default? 

We are using the [net.devh grpc spring boot starter](https://github.com/yidongnan/grpc-spring-boot-starter). All function calls originate from this line https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/ServerCalls.kt#L240 where the `launch` places calls onto `Dispatchers.Default`. This means that on a single core system we have 2 threads handling grpc calls. We dispatch all blocking calls onto a separate threadpool, `Dispatchers.IO` in most cases, but it looks like we are then blocked joining back into the threads on Dispatchers.Default.  

I'm guessing the answer is looking at how the spring boot starter constructs the context that gets passed to unary or stream handlers?

**Comment by lowasser** [comment]
The abstract class for the server, the `MyServerCoroutineImplBase`, has a constructor accepting a `CoroutineContext`.  That'd typically be where you inject the dispatcher of your choice (and any other appropriate context).
