### ISSUE TITLE
Generated server-side streaming functions are not suspending

### ISSUE THREAD

**Issue by ed-irl** [grpc/grpc-kotlin#630]
The 1.4.1 generator generates non-suspending functions for server-side streaming RPC's.

For example:
```
  rpc ListFoos(ListFoosRequest) returns (stream ListFoosResponse);
```

Will generate something like

```
fun listFoos(request: ListFoosRequest): Flow<ListFoosResponse>
```

Notice the function lacks the suspend keyword. The generator creates suspending functions for all other `AbstractCoroutineServerImpl` implementations (eg. unary, bidirectional streaming).

**Comment by lowasser** [comment]
If this generates `suspend` functions for bidirectional streaming, that is a bug.  Functions that return `Flow` should not usually themselves suspend.  This is discussed several times in e.g. https://kotlinlang.org/docs/flow.html#suspending-functions .

**Comment by lowasser** [comment]
[This behavior](https://github.com/grpc/grpc-kotlin/blob/master/compiler/src/main/java/io/grpc/kotlin/generator/GrpcClientStubGenerator.kt#L199) looks correct: the generated function should suspend if and only if the server response is unary.

Please re-open this issue if you can confirm that _bidirectional_ streams result in a `suspend` function, as that would be a bug.
