### ISSUE TITLE
Generate Kotlin source for .proto messages?

### ISSUE THREAD

**Issue by charbgr** [grpc/grpc-kotlin#64]
Is there a way to generate Kotlin files from a proto3 message? Like Java's protoc but for Kotlin files?

**Comment by chalin** [comment]
Once your gradle file is setup (for example, see [examples/build.gradle](https://github.com/grpc/grpc-kotlin/blob/master/examples/build.gradle)), then `protoc` will generate Kotlin sources from `.proto` files as part of the build.

If you build the [Hello World](https://grpc.io/docs/quickstart/kotlin/) example, the Kotlin source generated from

- `examples/src/main/proto/hello_world.proto`

will end up in 

- `examples/build/generated/source/proto/main/grpckt/io/grpc/examples/helloworld/HelloWorldGrpcKt.kt`:

  <img src="https://user-images.githubusercontent.com/4140793/79556966-c6028300-806f-11ea-85c1-ef248347a347.png" width=250>

**Comment by pavlospt** [comment]
@chalin I think what @charbgr meant, is if we are going to see in the near future, generation of `.proto` messages in Kotlin. Right now the gRPC Service spec is generated in Kotlin but the used messages are generated in Java.

**Comment by chalin** [comment]
Oh right -- so you really did mean to ask about messages in your original question. I'll let @lowasser answer in that case.

**Comment by lowasser** [comment]
We are deliberately separating the choice of Kotlin APIs for gRPC and the choice of Kotlin APIs for protobuf, as projects may choose to use one but not the other.

Support for Kotlin protos is being discussed in https://github.com/protocolbuffers/protobuf/issues/3742.

**Comment by chalin** [comment]
Given that this is being discussed elsewhere, can we close this issue?

**Comment by chalin** [comment]
> Support for Kotlin protos is being discussed in protocolbuffers/protobuf#3742.

FYI, we've added a note to the README about this (#70).
