### ISSUE TITLE
Is it required to set `java_multiple_files = true` option in proto definition

### ISSUE THREAD

**Issue by daneshk** [grpc/grpc-kotlin#67]
When I try to build the project without setting `java_multiple_files = true` option in proto definition, I got `Unresolved reference:` error. It seems like the generated code referring to message type like `<service-name>.<message-name>` but there is no java class generated with the service-name.

When I set the `java_multiple_files` option to true. The code generates correctly and builds successfully.

**Comment by chalin** [comment]
No, `java_multiple_files = true`, isn't required, but if you don't set this option, then your code will need access message types using a qualified name. For example, in the [Quick start Hello World](https://grpc.io/docs/quickstart/kotlin) client and server code, you'd access `HelloRequest` using the qualified name `HelloWorld.HelloRequest`.

Here are the changes required to allow the Hello World example to run without the `java_multiple_files = true` option in the `proto/hello_world.proto` file:

```diff
examples > git diff
diff --git a/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldClient.kt b/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldClient.kt
index 9e7628e..35f6b9f 100644
--- a/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldClient.kt
+++ b/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldClient.kt
@@ -33,7 +33,7 @@ class HelloWorldClient constructor(
   private val stub: GreeterCoroutineStub = GreeterCoroutineStub(channel)
 
   suspend fun greet(name: String) = coroutineScope {
-    val request = HelloRequest.newBuilder().setName(name).build()
+    val request = HelloWorld.HelloRequest.newBuilder().setName(name).build()
     val response = async { stub.sayHello(request) }
     println("Received: ${response.await().message}")
   }
diff --git a/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldServer.kt b/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldServer.kt
index 743488c..3f4b085 100644
--- a/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldServer.kt
+++ b/examples/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldServer.kt
@@ -48,7 +48,7 @@ class HelloWorldServer constructor(
   }
 
   private class HelloWorldService : GreeterGrpcKt.GreeterCoroutineImplBase() {
-    override suspend fun sayHello(request: HelloRequest) = HelloReply
+    override suspend fun sayHello(request: HelloWorld.HelloRequest) = HelloWorld.HelloReply
         .newBuilder()
         .setMessage("Hello ${request.name}")
         .build()
```

cc @lowasser @bshaffer

**Comment by daneshk** [comment]
Thanks, @chalin
Actually the error is coming from the generated Kotlin source. The error is `: Unresolved reference: HelloWorld`. because there is no generated `HelloWorld` class.
When we don't specify this option. All message types are generated inside `HelloWorldOuterClass` class. I think we need to refer that class in generated source code and my code. something like `HelloWorldOuterClass. HelloRequest`
Correct me if I am wrong.

**Comment by chalin** [comment]
I'm not getting that error when I drop `java_multiple_files = true` from `proto/hello_world.proto` and do a clean build. Ensure that you `clean` before you build; for example:

```console
examples $ ./gradlew clean installDist
```

**Comment by daneshk** [comment]
I think I found the issue.
The problem comes when the proto file name is equal to the service name define inside the proto file.
For example:
Let say we have a proto file called `hello_world.proto` and service definition inside the proto file like below
```proto
syntax = "proto3";

package io.grpc.examples.helloworld;

// The greeting service definition.
service HelloWorld {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```

Here proto filename is `hello_world.proto` and service name is `HelloWorld`. 

When we generate the code, Generated java class is `HelloWorldOuterClass.java`. but generated Kotlin file is referring to the `HelloWorld.HelloRequest` for the message type. which causes the `: Unresolved reference: HelloWorld`

**Comment by lowasser** [comment]
Sounds like a valid bug.

**Comment by tipshep7** [comment]
It's close I can feel it in my head. Mutherfuckers!

**Comment by tipshep7** [comment]
W

**Comment by tipshep7** [comment]
Storage.google.api
