### ISSUE TITLE
Trailers lost when throwing StatusException/StatusRuntimeException in coroutine server method

### ISSUE THREAD

**Issue by pkwarren** [grpc/grpc-kotlin#68]
Currently, trailing headers are lost when a coroutine gRPC method implementation sets trailers on a thrown StatusException/StatusRuntimeException. I believe the fix is to update this portion of the code to call `Status.trailersFromThrowable(failure)` and return it if non-null instead of always returning an empty `GrpcMetadata()`: https://github.com/grpc/grpc-kotlin/blob/be5c1d03b3580eb56efca0c04ea627fd4d6f906c/stub/src/main/java/io/grpc/kotlin/ServerCalls.kt#L253

**Comment by lowasser** [comment]
Excellent catch.  Fix in flight.
