### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#69]
It has been broken for a couple of days now:

![image](https://user-images.githubusercontent.com/4140793/79869470-6a0d6680-83af-11ea-8f43-ccad0577eee2.png)

cc @bshaffer

**Comment by lowasser** [comment]
Looking at it, it seems successful now: https://travis-ci.org/github/grpc/grpc-kotlin/builds/677791904

I diagnose a flake, not a real error, but still worth fixing.

**Comment by chalin** [comment]
From https://github.com/grpc/grpc-kotlin/pull/71#issuecomment-617354864 (sorry, I think that the questions are better asked here):

> These are the same tests as those used by grpc-java, right? How do they avoid the race condition or manage it?

**Comment by lowasser** [comment]
Resolved by #71 .
