### ISSUE TITLE
Automate deployment of API reference docs

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#74]
@jamesward spoke of adapting a deploy app that he wrote and used elsewhere. Deployment wouldn't be to gh-pages`.

@jamesward - once this is setup, and you know the link to the API reference docs, let me know so that I can make the corresponding update to the link used on the grpc.io site - https://github.com/grpc/grpc.io/issues/218

**Comment by chalin** [comment]
Depends on #73.

**Comment by jamesward** [comment]
This is live: https://javadocs.dev/io.grpc/grpc-kotlin-stub/0.1.2/

**Comment by chalin** [comment]
Nice! What triggers the deployment?

**Comment by jamesward** [comment]
Nothing.  It pulls from Maven Central on demand.

Once the Maven Central index updates then this will work too:
https://javadocs.dev/io.grpc/grpc-kotlin-stub/latest/

**Comment by bshaffer** [comment]
Can we close this one or is there still an action item here?

**Comment by jamesward** [comment]
Nope! We are good on this.
