### ISSUE TITLE
add support for grpc-protobuf-lite 

### ISSUE THREAD

**Issue by jagobagascon** [grpc/grpc-kotlin#80]
We are currently using gRPC on a Kotlin based Android project and as [grpc-java documentation](https://github.com/grpc/grpc-java#download) recommends we are using the lite version of the runtime (`grpc-protobuf-lite`).

Right now `grpc-kotlin-stub` depends on `grpc-protobuf` which causes our gradle build to fail if we don't explicitly exclude `grpc-protobuf` from `grpc-kotlin-stub`.

I don't like the idea of having to exclude transitive dependencies, are there any plans on releasing a `grpc-kotlin-stub-lite`?

**Comment by lowasser** [comment]
@bshaffer , is this done?

**Comment by bshaffer** [comment]
Added in [0.1.2](https://github.com/grpc/grpc-kotlin/releases/tag/v0.1.2)!
