### ISSUE TITLE
Remove native binarys and update instructions to use protoc jars

### ISSUE THREAD

**Issue by jamesward** [grpc/grpc-kotlin#82]
Canteen makes jars executable by preprending a launcher:
https://github.com/salesforce/grpc-java-contrib/tree/master/canteen

We'd need to build a gradle plugin for it.

Or, add jar support to the protobuf-gradle-plugin:
https://github.com/google/protobuf-gradle-plugin/issues/168

**Comment by Octogonapus** [comment]
Now that https://github.com/google/protobuf-gradle-plugin/issues/168 is closed, is it possible to implement this feature so that, ultimately, https://github.com/grpc/grpc-kotlin/issues/116 can be fixed?

**Comment by jamesward** [comment]
Thanks for the heads up! That was actually closed as fixed :)  So we won't need Canteen and can instead just use our protoc jars.  Updating the title to reflect this.

**Comment by jamesward** [comment]
For reference: https://github.com/google/protobuf-gradle-plugin/pull/423

**Comment by jamesward** [comment]
I think we should do a `0.2.0` release for this, migrate the samples & docs, and allow for good testing across platforms.  Then once validated aim for `1.0.0`.

Note that the syntax is:
```
artifact = "io.grpc:protoc-gen-grpc-kotlin:$grpcKotlinVersion:protoc@jar"
```

The classifier on the artifact in this case is `protoc` but I think there is some standard to instead make it like `jdk8` for a JDK 8 compatiable jar.

**Comment by jamesward** [comment]
BTW, this requires a new version of the Gradle Protobuf plugin (`0.8.13`):
```
id("com.google.protobuf") version "0.8.13"
```

**Comment by jamesward** [comment]
The samples in this repo have been updated to use this.  And here is the PR for updating the other kotlin samples: https://github.com/GoogleCloudPlatform/kotlin-samples/pull/78
