### ISSUE TITLE
Support for Kotlin DSL style builders

### ISSUE THREAD

**Issue by dariuszkuc** [grpc/grpc-kotlin#83]
Instead of relying on Java builders it would be great if this library supported Kotlin DSL, e.g. given

```
service HelloWorldAPI {
    rpc HelloWorld(HelloWorldRequest) returns (HelloWorldResponse);
}

message HelloWorldRequest {
    string hello_message = 1;
}

message HelloWorldResponse {
    string hello_response = 1;
}
```

It would be great if we could construct proto objects as 

```kotlin
val hello = HelloWorldRequest {
  helloMessage = "hello"
}
```

instead of using ugly Java builders

```kotlin
val hello = HelloWorldRequest.newBuilder()
  .setHelloMessage("hello")
  .build()
```

**Comment by lowasser** [comment]
This project is specifically for gRPC only, not for protocol buffers in general.   That project is happening separately, as mentioned in this project's readme: 

> Note: The Kotlin protoc plugin uses the Java protoc plugin behind the scenes to generate message types as Java classes. Generation of Kotlin sources for proto messages is being discussed in protocolbuffers/protobuf#3742.
