### ISSUE TITLE
Example on how to use gRPC context

### ISSUE THREAD

**Issue by nestorsokil** [grpc/grpc-kotlin#85]
What is the recommended way to use gRPC metadata?
I cannot see anything in the examples and want to figure out what is the safest way in terms of concurrency and backward compatibility.

**Comment by lowasser** [comment]
The only currently supported way to interact with metadata is via interceptors, which is done with the same APIs used in gRPC-Java.  See, for example, https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/header.

We see interacting with metadata as a relatively niche use case, and were in fact asked to _remove_ client access to metadata in #47 .

**Comment by nestorsokil** [comment]
@lowasser thanks for the tip, I'm actually familiar with the Java approach. What I'm trying to figure out is the best way to propagate this context to coroutines.

**Comment by lowasser** [comment]
I don't believe there is any way to do that at this time.

**Comment by lowasser** [comment]
Well, hmm.  If you really wanted to, on the server you could attach arbitrary information to the gRPC Context from an interceptor.  gRPC-Kotlin already takes care of making sure gRPC contexts and coroutines play nicely together, so that would work.

**Comment by nestorsokil** [comment]
@lowasser Yes, I found that out experimentally but wasn't exactly sure if what I was seeing is correct, so thank you for confirmation!

For history this is how to do this:
```
public class SharedContextServerInterceptor implements ServerInterceptor {
  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> serverCall, Metadata metadata, ServerCallHandler<ReqT, RespT> serverCallHandler) {
    Context ctx = Context.current();
    String value = metadata.get(io.grpc.Metadata.Key.of("whatever", Metadata.ASCII_STRING_MARSHALLER));
    ctx = ctx.withValue("whatever", value);
    return Contexts.interceptCall(ctx, serverCall, metadata, serverCallHandler);
  }
}

// in kt
override suspend fun handler(req: MyReq): MyResp {
   val whatever = Context.key("whatever").get()
   // ...
} 
```

**Comment by lowasser** [comment]
Fixed by the newly added interceptor API.

**Comment by asarkar** [comment]
@lowasser 
> newly added interceptor API

I'm unable to find any mention of this in the docs. Could you please elaborate?

**Comment by lowasser** [comment]
https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/CoroutineContextServerInterceptor.kt

Install a `CoroutineContextServerInterceptor` that translates the incoming metadata to whatever `CoroutineContext` is appropriate, including just a holder for the `Metadata`, if that's what you need.

**Comment by mancini0** [comment]
What should I return if I need to close the call if the interceptor fails some precondition? I think an interceptor example in the examples directory would be super helpful.  I'm currently using grpc-java's ServerInterceptor api but would like to move to CoroutineContextServerInterceptor - but I am not quite sure how to reconcile the differences in the approaches' signatures


Below is my grpc-java based interceptor that adds the caller's Firebase user id to the gRPC Context. (Retrieved from a base64 encoded JWT ...Istio decrypts and verifies the JWT and forwards the base64 encoded JWT payload to the application). If the user id (uid below) is not present, I close the call with an unauthenticated status and return a empty ServerCall.Listener.  I'm not sure how to accomplish the same functionality using the CoroutineContextServerInterceptor. 
```
  override fun <ReqT : Any, RespT : Any> interceptCall(call: ServerCall<ReqT, RespT>, headers: Metadata,
                                                         next: ServerCallHandler<ReqT, RespT>): ServerCall.Listener<ReqT> {
        headers.get(Metadata.Key.of(ENCODED_JWT_PAYLOAD_KEY,
                Metadata.ASCII_STRING_MARSHALLER))?.let {
            val uid = JsonParser.parseString(String(Base64.getDecoder().decode(it)))
                    .asJsonObject["sub"]?.asString
            val ctx = Context.current().withValue(UID_CTX_KEY, uid)
            return Contexts.interceptCall(ctx, call, headers, next)
        }
        call.close(Status.UNAUTHENTICATED, headers)
        return object : ServerCall.Listener<ReqT>() {}
    }
```

**Comment by lowasser** [comment]
Not sure, and not at a computer right now to check, but: try throwing a StatusException with the appropriate status.

**Comment by lowasser** [comment]
Actually, now that I look at it: the intended API is that you continue to write exactly the code above.  CoroutineContextServerInterceptor is intended only for a special case of interception where you specifically want to modify the CoroutineContext.

**Comment by lowasser** [comment]
That is, you should not migrate; it's not a migration, it's a separate feature.

**Comment by illeatmyhat** [comment]
> `val whatever = Context.key("whatever").get()`

FYI since this is apparently the only place on the internet explaining how to use headers in gRPC with kotlin:

Context.Keys are compared referentially, so if you set headers using a set of Context.Keys, as in [the `HeaderServerInterceptor` example](https://github.com/feuyeux/hello-grpc/blob/main/grpc/hello-grpc-kotlin/server/src/main/kotlin/org/feuyeux/grpc/HeaderServerInterceptor.kt#L16-L22), you need to use the exact same Key object or else `Context.Key.get()` will return `null`.

**Comment by kvcache** [comment]
> @illeatmyhat: FYI since this is apparently the only place on the internet explaining how to use headers in gRPC with kotlin:

Similarly, but with regard to context propagation in a server+client with async usage of client functions...
```kotlin
/**
 * For gRPC servers with gRPC backends.
 * gRPC contexts are hierarchical. When an inbound server call completes, gRPC cancels that context and this
 * cancellation cascades to all descendant contexts.
 * We return requests eagerly, and outbound calls to other gRPC servers originated by this server call might
 * still be in-flight when we return. While we handle appropriately separating coroutine scopes, there's this
 * extra poison element in the context you need to also handle in order to completely launch{} or async{}
 * Here we create a new context for processing requests which propagates the values of current context but does
 * not cascade its cancellation.
 * Note that one cannot use io.grpc.Context::attach/detach when using coroutines. Doing so like
 * ```kotlin
 * val local = Context.current().fork()
 * val previous = local.attach()
 * try { block() }
 * finally { local.detach(previous) }
 * ```
 * as the grpc docs would perhaps lead you to try is a trap. If you don't also tell the coroutine context
 * which threadlocal grpc context to use, then the context that is restored on coroutine resume has no
 * relationship to the context you forked other than that, if the new one is non-ROOT (meaning something
 * else also ran on this thread), they both ran in the same threadpool...
 * This is pretty gnarly between Kotlin Coroutines context, GRPC context and OpenTelemetry context.
 * You can easily imagine a launchWithForkedGrpcContext and asyncWithForkedGrpcContext as well if you have
 * a need only to couple a forked grpc context with a launch{} or async{}.
 */
private suspend inline fun <T> withForkedGrpcContext(crossinline block: suspend () -> T): T {
    return withContext(io.grpc.kotlin.GrpcContextElement(io.grpc.Context.current().fork())) {
        block()
    }
}
```

[The CoroutineContextServerInterceptor](https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/CoroutineContextServerInterceptor.kt) really broadly alludes to this but it's unclear (to me) at a glance what a person is supposed to glean from it for a forking use case. I wish grpc didn't use threadlocals to pass arguments down a stack :-(

**Comment by o-nix** [comment]
Oof, guys, that was not so easy to understand and properly add.

I really needed headers in the business code, so they are sent back to the gRPC Gateway. Not sure why you call it "niche" use-case.

```kotlin
object CustomHeadersInterceptor : ServerInterceptor {
    // Class which helps to get access to the gRPC request information and store new headers in coroutine context.
    class GrpcInternalRequestDataCoroutineContext(
        val requestHeaders: Metadata,
        val responseHeaders: MutableMap<String, String> = mutableMapOf()
    ) : AbstractCoroutineContextElement(GrpcInternalRequestDataCoroutineContext) {
        companion object Key : CoroutineContext.Key<GrpcInternalRequestDataCoroutineContext>
    }

    // The parent in the coroutines tree, which will propagate the context with new headers down the tree.
    class ExtraCoroutineContextDataInterceptor(private val requestDataCoroutineContext: GrpcInternalRequestDataCoroutineContext) :
        CoroutineContextServerInterceptor() {
        override fun coroutineContext(call: ServerCall<*, *>, headers: Metadata): CoroutineContext {
            return requestDataCoroutineContext
        }
    }

    // Non-suspending interceptor which will be called for each incoming call.
    override fun <ReqT : Any?, RespT : Any?> interceptCall(
        call: ServerCall<ReqT, RespT>,
        headers: Metadata,
        next: ServerCallHandler<ReqT, RespT>
    ): ServerCall.Listener<ReqT> {
        val newHeadersContext = GrpcInternalRequestDataCoroutineContext(requestHeaders = headers)
        val interceptor = ExtraCoroutineContextDataInterceptor(newHeadersContext)

        val customForwardingCall = object : SimpleForwardingServerCall<ReqT, RespT>(call) {
            override fun sendHeaders(responseHeaders: Metadata) {
                newHeadersContext.responseHeaders.forEach { (key, value) ->
                    responseHeaders.put(
                        Metadata.Key.of(key, Metadata.ASCII_STRING_MARSHALLER),
                        value
                    )
                }

                super.sendHeaders(responseHeaders)
            }
        }

        val handlerForCoroutineBased = ServerCallHandler<ReqT, RespT> { _, h ->
            next.startCall(customForwardingCall, h)
        }

        // Call the coroutine-based interceptor from the non-suspending one.
        return interceptor.interceptCall(call, headers, handlerForCoroutineBased)
    }
}

@Suppress("UnusedReceiverParameter")
suspend inline fun AbstractCoroutineServerImpl.setHeader(key: String, value: String) {
    currentCoroutineContext()[GrpcInternalRequestDataCoroutineContext]!!.responseHeaders[key] = value
}

@Suppress("UnusedReceiverParameter")
suspend inline fun AbstractCoroutineServerImpl.getHeader(key: String): String? {
    return currentCoroutineContext()[GrpcInternalRequestDataCoroutineContext]!!.requestHeaders.get(
        Metadata.Key.of(
            key,
            Metadata.ASCII_STRING_MARSHALLER
        )
    )
}

...

class MyServiceImpl : MyServiceGrpcKt.MyServiceCoroutineImplBase() {
    override fun doSomethingUsefulStreamed(request: DoSomethingUsefulRequest): Flow<HttpBody> {
        return flow {
            val incoming = getHeader("X-Custom-Incoming-Header")
            setHeader("X-Custom-Outgoing-Header", "useful value to the client")

            ...
        }
    }
}
```
