### ISSUE TITLE
mismatch between `grpc-java` protobuf generated classes and `grpc-kotlin` expected classes

### ISSUE THREAD

**Issue by dariuszkuc** [grpc/grpc-kotlin#92]
Unsure whether this should be created under protobuf or grpc-kotlin but given simple `hello.proto`

```
syntax = "proto3";

option java_multiple_files = false;
package hello;

service Hello {
    rpc hello(Request) returns (Response);
}

message Request {
    string name = 1;
}

message Response {
    string greeting = 1;
}
```

GRPC Java generates wrapper `HelloOuterClass` for `Request` and `Response` messages whereas GRPC Kotlin expects wrapper class to be just `Hello` which leads to compilation errors. Simplest workaround is to rename the proto file which then results in consistent wrapper classes.

Sample project:
https://github.com/dariuszkuc/grpc-kotlin-issue

**Comment by lowasser** [comment]
I believe this to be a duplicate of #67 , which has been fixed but the fix hasn't been released yet.
