### ISSUE TITLE
Add example with build.gradle.kts configuration

### ISSUE THREAD

**Issue by tagantroy** [grpc/grpc-kotlin#99]
Existing example project based on groovy Gradle configuration. Kotlin script support added long time ago to Gradle https://docs.gradle.org/current/userguide/kotlin_dsl.html. 
It would be nice to have kts example too

**Comment by jamesward** [comment]
I've updated a sample to use kts:
https://github.com/jamesward/kotlin-samples/tree/kts/run/grpc-hello-world-gradle

But it would be nice to officially convert all samples to use kts.

**Comment by chalin** [comment]
Do you think that you'll get to this soon @jamesward?

**Comment by jamesward** [comment]
PR for this repo: https://github.com/grpc/grpc-kotlin/pull/120
The GCP samples have been converted: https://github.com/GoogleCloudPlatform/kotlin-samples/tree/master/run
